-- DEMO / SYNTHETIC DATA. Generated by build_demo_seed.py; no real hospital records.
-- Hospital-style department names are generic; all entities/ownership are synthetic.

INSERT INTO department (code, name, active)
VALUES
  ('KHOA_NOI', 'Khoa Nội', TRUE),
  ('PHONG_VTYT', 'Phòng Vật tư Y tế', TRUE),
  ('CAP_CUU', 'Khoa Cấp cứu', TRUE),
  ('HOI_SUC', 'Khoa Hồi sức tích cực', TRUE),
  ('CHAN_DOAN_HINH_ANH', 'Khoa Chẩn đoán hình ảnh', TRUE),
  ('XET_NGHIEM', 'Khoa Xét nghiệm', TRUE),
  ('PHAU_THUAT', 'Khoa Phẫu thuật - Gây mê hồi sức', TRUE),
  ('KHOA_NGOAI', 'Khoa Ngoại', TRUE);

-- All provider organizations are fictional demo labels; no actual contract is implied.

INSERT INTO service_provider (code, name, contact_details, active)
VALUES
  ('DEMO_PROVIDER_01', 'Đơn vị bảo trì hợp đồng demo', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE),
  ('DEMO_PROVIDER_02', 'Đơn vị bảo trì ngoài demo', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE),
  ('DEMO_PROVIDER_03', 'Công ty Kỹ thuật Y sinh Minh An (Demo)', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE),
  ('DEMO_PROVIDER_04', 'Dịch vụ Thiết bị An Tâm (Demo)', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE),
  ('DEMO_PROVIDER_05', 'Kỹ thuật Chẩn đoán Sao Việt (Demo)', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE),
  ('DEMO_PROVIDER_06', 'Bảo trì Xét nghiệm Minh Khoa (Demo)', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE),
  ('DEMO_PROVIDER_07', 'Giải pháp Trang thiết bị Hòa Bình (Demo)', 'Liên hệ giả lập; không dùng để liên hệ thực tế', TRUE);

-- Bcrypt hashes came from discarded random inputs; no login password is available.

INSERT INTO user_account (department_id, role_code, username, password_hash, display_name, active)
VALUES
  ((SELECT id FROM department WHERE code='PHONG_VTYT'), 'PHONG_VTYT', 'demo_vtyt', '$2b$12$kUQL6IIEZoH/hRU59Ug.T.oWm2kU2jWhRS6xjpUIZBBLPPO.z0cTa', 'Nhân viên VTYT demo', TRUE),
  (NULL, 'BAN_GIAM_DOC', 'demo_bgd', '$2b$12$91R5yjSB.tZQ/PzWuy3yLubUPZYZkd3es1rE8K1VGrbOnPBatacJq', 'Ban Giám đốc demo', TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NOI'), 'KHOA_PHONG', 'demo_khoa_noi', '$2b$12$YJOEMu1Q.xs2P8IZ4dhtte255ay0B0SSCa28EnPUPWqfO7udM7Hhm', 'Đại diện Khoa Nội demo', TRUE),
  ((SELECT id FROM department WHERE code='PHONG_VTYT'), 'ADMIN', 'demo_admin', '$2b$12$pzJdR2guVuhGrlv.3woEbOPbSXFmgqEDJPxUofW7t4a7N.kuYycBS', 'Quản trị demo', TRUE),
  ((SELECT id FROM department WHERE code='PHONG_VTYT'), 'PHONG_VTYT', 'vtyt_demo02', '$2b$12$1A6ELaOaS./dEQmguY/4dOJ4Xxmv3DvilEw4wsxtgYb2bd1lKILHi', 'Nhân viên VTYT demo 02', TRUE),
  ((SELECT id FROM department WHERE code='PHONG_VTYT'), 'PHONG_VTYT', 'vtyt_demo03', '$2b$12$/r/Bv7H9WvOYiZjUfHCsbuUccWGFevgT76awBDqh0gwdbcoZPEqwS', 'Nhân viên VTYT demo 03', TRUE),
  ((SELECT id FROM department WHERE code='PHONG_VTYT'), 'PHONG_VTYT', 'vtyt_demo04', '$2b$12$4FMDD3qfXuBrG0BcY7qaGusLIlJURoIxGvxXZWwQYSeUhg9mSL4Qa', 'Nhân viên VTYT demo 04', TRUE),
  (NULL, 'BAN_GIAM_DOC', 'bgd_demo02', '$2b$12$I6vUnpYsxMgJPxnHGRuBS.FXXfzK2/lkhkOs8jMKSZVk9uGC9362e', 'Ban Giám đốc demo 02', TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'KHOA_PHONG', 'khoa_cc_demo01', '$2b$12$OabJRqPvtwLYarpEeRO7WuVVZCVsDmEO/p5CYi6vBUKSfc9Og1DmG', 'Đại diện Cấp cứu demo', TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'KHOA_PHONG', 'khoa_hs_demo01', '$2b$12$D150IBgqHWSaEabWXQzel.mWwBX13XBrIM5arqDcUXptsOwxJrMbK', 'Đại diện Hồi sức demo', TRUE),
  ((SELECT id FROM department WHERE code='CHAN_DOAN_HINH_ANH'), 'KHOA_PHONG', 'khoa_cd_demo01', '$2b$12$uOG7nh2KxhUawL2/aSTBCuZePLFSdS6svmcIA7vt0ni086xDhTfYq', 'Đại diện Chẩn đoán hình ảnh demo', TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'KHOA_PHONG', 'khoa_xn_demo01', '$2b$12$bwrwTkUtzutpvz/i23yJgOYIOyz2yfFQa7gM/cxoAbR.1FTJcnJsq', 'Đại diện Xét nghiệm demo', TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'KHOA_PHONG', 'khoa_pt_demo01', '$2b$12$BrRu7xKt5fG3KO1AWhktl.CX5pwELga49D1N9KNg2d3DVjMogahfq', 'Đại diện Phẫu thuật demo', TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NGOAI'), 'KHOA_PHONG', 'khoa_ngoai_demo01', '$2b$12$WNmyKuIdPR2NDDC5LwX/UOy2s7ttZ5dyutOZDiuwBrJqBYNtDhj0a', 'Đại diện Khoa Ngoại demo', TRUE),
  ((SELECT id FROM department WHERE code='PHONG_VTYT'), 'ADMIN', 'admin_demo02', '$2b$12$B45AZU0NfjsN5U/dqF9lKOHPBLBUOPmT4i/2ETzvz/BExLYT0mVL.', 'Quản trị demo 02', TRUE);

-- Public model labels are reference-inspired; asset identity and department are synthetic.

INSERT INTO equipment (department_id, equipment_code, name, serial_number, model, technical_spec, active)
VALUES
  ((SELECT id FROM department WHERE code='KHOA_NOI'), 'DEMO-EQ-001', 'Máy theo dõi bệnh nhân', 'SYN-SN-0001', 'DEMO-GENERIC-MONITOR', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NOI'), 'DEMO-EQ-002', 'Bơm tiêm điện', 'SYN-SN-0002', 'DEMO-GENERIC-SYRINGE', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NOI'), 'DEMO-EQ-003', 'Máy điện tim', 'SYN-SN-0003', 'DEMO-GENERIC-ECG', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-004', 'Máy sốc điện', 'SYN-SN-0004', 'Nihon Kohden Cardiolife TEC-8300', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-005', 'Máy sốc điện', 'SYN-SN-0005', 'Nihon Kohden Cardiolife TEC-8300', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-006', 'Máy điện tim', 'SYN-SN-0006', 'DEMO-GENERIC-ECG', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-007', 'Máy điện tim', 'SYN-SN-0007', 'DEMO-GENERIC-ECG', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-008', 'Máy theo dõi bệnh nhân', 'SYN-SN-0008', 'Philips IntelliVue MX450', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-009', 'Máy theo dõi bệnh nhân', 'SYN-SN-0009', 'Philips IntelliVue MX450', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CAP_CUU'), 'DEMO-EQ-010', 'Bơm tiêm điện', 'SYN-SN-0010', 'B. Braun Spaceplus Perfusor', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-011', 'Máy thở', 'SYN-SN-0011', 'Dräger Evita V600', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-012', 'Máy thở', 'SYN-SN-0012', 'Dräger Evita V600', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-013', 'Máy theo dõi bệnh nhân', 'SYN-SN-0013', 'Philips IntelliVue MX450', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-014', 'Máy theo dõi bệnh nhân', 'SYN-SN-0014', 'Philips IntelliVue MX450', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-015', 'Bơm truyền dịch', 'SYN-SN-0015', 'B. Braun Spaceplus Infusomat', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-016', 'Bơm truyền dịch', 'SYN-SN-0016', 'B. Braun Spaceplus Infusomat', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-017', 'Bơm tiêm điện', 'SYN-SN-0017', 'B. Braun Spaceplus Perfusor', NULL, TRUE),
  ((SELECT id FROM department WHERE code='HOI_SUC'), 'DEMO-EQ-018', 'Bơm tiêm điện', 'SYN-SN-0018', 'B. Braun Spaceplus Perfusor', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CHAN_DOAN_HINH_ANH'), 'DEMO-EQ-019', 'Máy siêu âm', 'SYN-SN-0019', 'GE HealthCare Venue Go', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CHAN_DOAN_HINH_ANH'), 'DEMO-EQ-020', 'Máy siêu âm', 'SYN-SN-0020', 'GE HealthCare Venue Go', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CHAN_DOAN_HINH_ANH'), 'DEMO-EQ-021', 'Máy siêu âm', 'SYN-SN-0021', 'GE HealthCare Venue Go', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CHAN_DOAN_HINH_ANH'), 'DEMO-EQ-022', 'Hệ thống X-quang', 'SYN-SN-0022', 'DEMO-GENERIC-XRAY', NULL, TRUE),
  ((SELECT id FROM department WHERE code='CHAN_DOAN_HINH_ANH'), 'DEMO-EQ-023', 'Hệ thống X-quang', 'SYN-SN-0023', 'DEMO-GENERIC-XRAY', NULL, TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'DEMO-EQ-024', 'Máy xét nghiệm sinh hóa', 'SYN-SN-0024', 'Roche cobas c 311', NULL, TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'DEMO-EQ-025', 'Máy xét nghiệm sinh hóa', 'SYN-SN-0025', 'Roche cobas c 311', NULL, TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'DEMO-EQ-026', 'Máy xét nghiệm huyết học', 'SYN-SN-0026', 'Sysmex XN-1000', NULL, TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'DEMO-EQ-027', 'Máy xét nghiệm huyết học', 'SYN-SN-0027', 'Sysmex XN-1000', NULL, TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'DEMO-EQ-028', 'Máy ly tâm', 'SYN-SN-0028', 'DEMO-GENERIC-CENTRIFUGE', NULL, TRUE),
  ((SELECT id FROM department WHERE code='XET_NGHIEM'), 'DEMO-EQ-029', 'Máy ly tâm', 'SYN-SN-0029', 'DEMO-GENERIC-CENTRIFUGE', NULL, TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'DEMO-EQ-030', 'Máy gây mê', 'SYN-SN-0030', 'DEMO-GENERIC-ANESTHESIA', NULL, TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'DEMO-EQ-031', 'Máy gây mê', 'SYN-SN-0031', 'DEMO-GENERIC-ANESTHESIA', NULL, TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'DEMO-EQ-032', 'Dao mổ điện', 'SYN-SN-0032', 'DEMO-GENERIC-ELECTROSURGERY', NULL, TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'DEMO-EQ-033', 'Dao mổ điện', 'SYN-SN-0033', 'DEMO-GENERIC-ELECTROSURGERY', NULL, TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'DEMO-EQ-034', 'Máy theo dõi bệnh nhân', 'SYN-SN-0034', 'Philips IntelliVue MX450', NULL, TRUE),
  ((SELECT id FROM department WHERE code='PHAU_THUAT'), 'DEMO-EQ-035', 'Bơm tiêm điện', 'SYN-SN-0035', 'B. Braun Spaceplus Perfusor', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NOI'), 'DEMO-EQ-036', 'Bơm truyền dịch', 'SYN-SN-0036', 'B. Braun Spaceplus Infusomat', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NOI'), 'DEMO-EQ-037', 'Máy tạo oxy', 'SYN-SN-0037', 'DEMO-GENERIC-OXYGEN', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NGOAI'), 'DEMO-EQ-038', 'Nồi hấp tiệt khuẩn', 'SYN-SN-0038', 'DEMO-GENERIC-STERILIZER', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NGOAI'), 'DEMO-EQ-039', 'Nồi hấp tiệt khuẩn', 'SYN-SN-0039', 'DEMO-GENERIC-STERILIZER', NULL, TRUE),
  ((SELECT id FROM department WHERE code='KHOA_NGOAI'), 'DEMO-EQ-040', 'Máy theo dõi bệnh nhân', 'SYN-SN-0040', 'Philips IntelliVue MX450', NULL, TRUE);
