#!/usr/bin/env python3
"""Deterministically render the Phase 1.3 synthetic demo SQL files.

Run only when editing the dataset. Runtime seeding executes the generated SQL files.
No passwords, patient records, or private hospital records are used.
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TZ = timezone(timedelta(hours=7))

class Raw(str):
    pass

def q(value):
    if isinstance(value, Raw): return str(value)
    if value is None: return 'NULL'
    if isinstance(value, bool): return 'TRUE' if value else 'FALSE'
    if isinstance(value, int): return str(value)
    return "'" + str(value).replace("'", "''") + "'"

def T(y,m,d,h=8,mi=0,sec=0): return datetime(y,m,d,h,mi,sec,tzinfo=TZ)
def TS(value): return Raw("TIMESTAMPTZ " + q(value.strftime('%Y-%m-%d %H:%M:%S+07')))
def D(value): return Raw('DATE ' + q(value))
def ref(table,column,value): return Raw(f'(SELECT id FROM {table} WHERE {column}={q(value)})')
def dept(code): return ref('department','code',code)
def user(name): return ref('user_account','username',name)
def provider(name): return ref('service_provider','name',name)
def equipment(code): return ref('equipment','equipment_code',code)
def plan(title): return ref('maintenance_plan','title',title)
def coverage(code): return Raw(f'(SELECT c.id FROM maintenance_coverage c JOIN equipment e ON e.id=c.equipment_id WHERE e.equipment_code={q(code)})')
def item_ref(plan_title,code):
    return Raw(f'(SELECT i.id FROM maintenance_plan_item i JOIN maintenance_plan p ON p.id=i.plan_id JOIN equipment e ON e.id=i.equipment_id WHERE p.title={q(plan_title)} AND e.equipment_code={q(code)})')
def exec_ref(plan_title,code,attempt):
    return Raw(f'(SELECT x.id FROM maintenance_execution x WHERE x.plan_item_id={item_ref(plan_title,code)} AND x.attempt_no={attempt})')

def insert(table, row):
    cols=', '.join(row)
    vals=', '.join(q(v) for v in row.values())
    return f'INSERT INTO {table} ({cols})\nVALUES ({vals});'

def batch(table,columns,rows):
    if not rows: return ''
    out=[f'INSERT INTO {table} ({", ".join(columns)})', 'VALUES']
    for i,row in enumerate(rows):
        out.append('  ('+', '.join(q(v) for v in row)+(');' if i==len(rows)-1 else '),'))
    return '\n'.join(out)

def write(name, sections):
    path=ROOT/name
    path.write_text('-- DEMO / SYNTHETIC DATA. Generated by build_demo_seed.py; no real hospital records.\n'
                    + '\n\n'.join(sections)+'\n',encoding='utf-8')

# Department names are generic Vietnamese hospital terminology, not an actual org chart.
depts=[
('KHOA_NOI','Khoa Nội'),('PHONG_VTYT','Phòng Vật tư Y tế'),
('CAP_CUU','Khoa Cấp cứu'),('HOI_SUC','Khoa Hồi sức tích cực'),
('CHAN_DOAN_HINH_ANH','Khoa Chẩn đoán hình ảnh'),('XET_NGHIEM','Khoa Xét nghiệm'),
('PHAU_THUAT','Khoa Phẫu thuật - Gây mê hồi sức'),('KHOA_NGOAI','Khoa Ngoại')]
providers=[
'Đơn vị bảo trì hợp đồng demo','Đơn vị bảo trì ngoài demo',
'Công ty Kỹ thuật Y sinh Minh An (Demo)','Dịch vụ Thiết bị An Tâm (Demo)',
'Kỹ thuật Chẩn đoán Sao Việt (Demo)','Bảo trì Xét nghiệm Minh Khoa (Demo)',
'Giải pháp Trang thiết bị Hòa Bình (Demo)']
hashes=[
'$2b$12$kUQL6IIEZoH/hRU59Ug.T.oWm2kU2jWhRS6xjpUIZBBLPPO.z0cTa',
'$2b$12$91R5yjSB.tZQ/PzWuy3yLubUPZYZkd3es1rE8K1VGrbOnPBatacJq',
'$2b$12$YJOEMu1Q.xs2P8IZ4dhtte255ay0B0SSCa28EnPUPWqfO7udM7Hhm',
'$2b$12$pzJdR2guVuhGrlv.3woEbOPbSXFmgqEDJPxUofW7t4a7N.kuYycBS',
'$2b$12$1A6ELaOaS./dEQmguY/4dOJ4Xxmv3DvilEw4wsxtgYb2bd1lKILHi',
'$2b$12$/r/Bv7H9WvOYiZjUfHCsbuUccWGFevgT76awBDqh0gwdbcoZPEqwS',
'$2b$12$4FMDD3qfXuBrG0BcY7qaGusLIlJURoIxGvxXZWwQYSeUhg9mSL4Qa',
'$2b$12$I6vUnpYsxMgJPxnHGRuBS.FXXfzK2/lkhkOs8jMKSZVk9uGC9362e',
'$2b$12$OabJRqPvtwLYarpEeRO7WuVVZCVsDmEO/p5CYi6vBUKSfc9Og1DmG',
'$2b$12$D150IBgqHWSaEabWXQzel.mWwBX13XBrIM5arqDcUXptsOwxJrMbK',
'$2b$12$uOG7nh2KxhUawL2/aSTBCuZePLFSdS6svmcIA7vt0ni086xDhTfYq',
'$2b$12$bwrwTkUtzutpvz/i23yJgOYIOyz2yfFQa7gM/cxoAbR.1FTJcnJsq',
'$2b$12$BrRu7xKt5fG3KO1AWhktl.CX5pwELga49D1N9KNg2d3DVjMogahfq',
'$2b$12$WNmyKuIdPR2NDDC5LwX/UOy2s7ttZ5dyutOZDiuwBrJqBYNtDhj0a',
'$2b$12$B45AZU0NfjsN5U/dqF9lKOHPBLBUOPmT4i/2ETzvz/BExLYT0mVL.']
users=[
('demo_vtyt','PHONG_VTYT','PHONG_VTYT','Nhân viên VTYT demo'),
('demo_bgd','BAN_GIAM_DOC',None,'Ban Giám đốc demo'),
('demo_khoa_noi','KHOA_PHONG','KHOA_NOI','Đại diện Khoa Nội demo'),
('demo_admin','ADMIN','PHONG_VTYT','Quản trị demo'),
('vtyt_demo02','PHONG_VTYT','PHONG_VTYT','Nhân viên VTYT demo 02'),
('vtyt_demo03','PHONG_VTYT','PHONG_VTYT','Nhân viên VTYT demo 03'),
('vtyt_demo04','PHONG_VTYT','PHONG_VTYT','Nhân viên VTYT demo 04'),
('bgd_demo02','BAN_GIAM_DOC',None,'Ban Giám đốc demo 02'),
('khoa_cc_demo01','KHOA_PHONG','CAP_CUU','Đại diện Cấp cứu demo'),
('khoa_hs_demo01','KHOA_PHONG','HOI_SUC','Đại diện Hồi sức demo'),
('khoa_cd_demo01','KHOA_PHONG','CHAN_DOAN_HINH_ANH','Đại diện Chẩn đoán hình ảnh demo'),
('khoa_xn_demo01','KHOA_PHONG','XET_NGHIEM','Đại diện Xét nghiệm demo'),
('khoa_pt_demo01','KHOA_PHONG','PHAU_THUAT','Đại diện Phẫu thuật demo'),
('khoa_ngoai_demo01','KHOA_PHONG','KHOA_NGOAI','Đại diện Khoa Ngoại demo'),
('admin_demo02','ADMIN','PHONG_VTYT','Quản trị demo 02')]
assert len(users)==len(hashes)==15
signer_by_dept={'KHOA_NOI':'demo_khoa_noi','CAP_CUU':'khoa_cc_demo01','HOI_SUC':'khoa_hs_demo01',
'CHAN_DOAN_HINH_ANH':'khoa_cd_demo01','XET_NGHIEM':'khoa_xn_demo01',
'PHAU_THUAT':'khoa_pt_demo01','KHOA_NGOAI':'khoa_ngoai_demo01'}

# Model names in the second field are either documented public products or labelled DEMO.
E=[]
def eq(n,department,category,model):
    E.append({'code':f'DEMO-EQ-{n:03d}','dept':department,'name':category,'model':model})
eq(1,'KHOA_NOI','Máy theo dõi bệnh nhân','DEMO-GENERIC-MONITOR')
eq(2,'KHOA_NOI','Bơm tiêm điện','DEMO-GENERIC-SYRINGE')
eq(3,'KHOA_NOI','Máy điện tim','DEMO-GENERIC-ECG')
for n,cat,model in [
(4,'Máy sốc điện','Nihon Kohden Cardiolife TEC-8300'),(5,'Máy sốc điện','Nihon Kohden Cardiolife TEC-8300'),
(6,'Máy điện tim','DEMO-GENERIC-ECG'),(7,'Máy điện tim','DEMO-GENERIC-ECG'),
(8,'Máy theo dõi bệnh nhân','Philips IntelliVue MX450'),(9,'Máy theo dõi bệnh nhân','Philips IntelliVue MX450'),
(10,'Bơm tiêm điện','B. Braun Spaceplus Perfusor')]: eq(n,'CAP_CUU',cat,model)
for n,cat,model in [
(11,'Máy thở','Dräger Evita V600'),(12,'Máy thở','Dräger Evita V600'),
(13,'Máy theo dõi bệnh nhân','Philips IntelliVue MX450'),(14,'Máy theo dõi bệnh nhân','Philips IntelliVue MX450'),
(15,'Bơm truyền dịch','B. Braun Spaceplus Infusomat'),(16,'Bơm truyền dịch','B. Braun Spaceplus Infusomat'),
(17,'Bơm tiêm điện','B. Braun Spaceplus Perfusor'),(18,'Bơm tiêm điện','B. Braun Spaceplus Perfusor')]: eq(n,'HOI_SUC',cat,model)
for n,cat,model in [
(19,'Máy siêu âm','GE HealthCare Venue Go'),(20,'Máy siêu âm','GE HealthCare Venue Go'),
(21,'Máy siêu âm','GE HealthCare Venue Go'),(22,'Hệ thống X-quang','DEMO-GENERIC-XRAY'),
(23,'Hệ thống X-quang','DEMO-GENERIC-XRAY')]: eq(n,'CHAN_DOAN_HINH_ANH',cat,model)
for n,cat,model in [
(24,'Máy xét nghiệm sinh hóa','Roche cobas c 311'),(25,'Máy xét nghiệm sinh hóa','Roche cobas c 311'),
(26,'Máy xét nghiệm huyết học','Sysmex XN-1000'),(27,'Máy xét nghiệm huyết học','Sysmex XN-1000'),
(28,'Máy ly tâm','DEMO-GENERIC-CENTRIFUGE'),(29,'Máy ly tâm','DEMO-GENERIC-CENTRIFUGE')]: eq(n,'XET_NGHIEM',cat,model)
for n,cat,model in [
(30,'Máy gây mê','DEMO-GENERIC-ANESTHESIA'),(31,'Máy gây mê','DEMO-GENERIC-ANESTHESIA'),
(32,'Dao mổ điện','DEMO-GENERIC-ELECTROSURGERY'),(33,'Dao mổ điện','DEMO-GENERIC-ELECTROSURGERY'),
(34,'Máy theo dõi bệnh nhân','Philips IntelliVue MX450'),(35,'Bơm tiêm điện','B. Braun Spaceplus Perfusor')]: eq(n,'PHAU_THUAT',cat,model)
eq(36,'KHOA_NOI','Bơm truyền dịch','B. Braun Spaceplus Infusomat')
eq(37,'KHOA_NOI','Máy tạo oxy','DEMO-GENERIC-OXYGEN')
eq(38,'KHOA_NGOAI','Nồi hấp tiệt khuẩn','DEMO-GENERIC-STERILIZER')
eq(39,'KHOA_NGOAI','Nồi hấp tiệt khuẩn','DEMO-GENERIC-STERILIZER')
eq(40,'KHOA_NGOAI','Máy theo dõi bệnh nhân','Philips IntelliVue MX450')
assert len(E)==40
EQ={int(e['code'][-3:]):e for e in E}

C={}
# Compatibility records from Phase 1.2 keep its assertion fixtures stable.
C[1]={'class':'FREE','provider':providers[0],'verified':T(2026,9,1,8),'from':'2026-01-01','to':'2026-12-31'}
C[2]={'class':'NOT_FREE','provider':None,'verified':T(2026,9,1,8),'from':'2026-01-01','to':'2026-12-31'}
C[3]={'class':'UNKNOWN','provider':None,'verified':None,'from':None,'to':None}
pattern=['FREE','FREE','NOT_FREE','FREE','NOT_FREE','UNKNOWN','NOT_FREE']
for n in range(4,36):
    cl=pattern[(n-4)%7]
    C[n]={'class':cl,'provider':providers[2+(n%5)] if cl=='FREE' else None,
          'verified':T(2025,12,15,10,n%50) if cl!='UNKNOWN' else None,
          'from':'2025-01-01' if cl!='UNKNOWN' else None,
          'to':'2026-12-31' if cl!='UNKNOWN' else None}
assert len(C)==35

P={
'p0':{'title':'DEMO — Kế hoạch bảo trì tháng 09/2026','from':'2026-09-01','to':'2026-09-30','created':T(2026,9,1,8),
      'events':[(T(2026,9,1,8),'DRAFT','CREATE',None,'demo_vtyt')]},
'p1':{'title':'DEMO — Bảo trì quý I/2026','from':'2026-01-01','to':'2026-03-31','created':T(2025,12,20,9),
      'events':[(T(2025,12,20,9),'DRAFT','CREATE',None,'demo_vtyt'),(T(2025,12,21,10),'SUBMITTED','SUBMIT_PLAN',None,'demo_vtyt'),(T(2025,12,22,10,5),'APPROVED','RECORD_APPROVAL',None,'demo_bgd'),(T(2026,1,5,8),'IN_PROGRESS','START_CAMPAIGN',None,'demo_vtyt'),(T(2026,3,15,8),'AWAITING_REPORT','CLOSE_FIELDWORK',None,'demo_vtyt'),(T(2026,3,21,9),'REPORTED','FINALIZE_REPORT',None,'demo_vtyt'),(T(2026,3,25,9),'CLOSED','CLOSE_PLAN',None,'demo_vtyt')]},
'p2':{'title':'DEMO — Bảo trì quý II/2026','from':'2026-04-01','to':'2026-06-30','created':T(2026,3,20,9),
      'events':[(T(2026,3,20,9),'DRAFT','CREATE',None,'vtyt_demo02'),(T(2026,3,21,10),'SUBMITTED','SUBMIT_PLAN',None,'vtyt_demo02'),(T(2026,3,22,10,5),'APPROVED','RECORD_APPROVAL',None,'bgd_demo02'),(T(2026,4,1,8),'IN_PROGRESS','START_CAMPAIGN',None,'vtyt_demo02'),(T(2026,6,10,8),'AWAITING_REPORT','CLOSE_FIELDWORK',None,'vtyt_demo02'),(T(2026,6,21,9),'REPORTED','FINALIZE_REPORT',None,'vtyt_demo02')]},
'p3':{'title':'DEMO — Bảo trì tháng 07/2026','from':'2026-07-01','to':'2026-07-31','created':T(2026,6,20,9),
      'events':[(T(2026,6,20,9),'DRAFT','CREATE',None,'vtyt_demo03'),(T(2026,6,21,10),'SUBMITTED','SUBMIT_PLAN',None,'vtyt_demo03'),(T(2026,6,22,10,5),'APPROVED','RECORD_APPROVAL',None,'demo_bgd'),(T(2026,7,1,8),'IN_PROGRESS','START_CAMPAIGN',None,'vtyt_demo03'),(T(2026,7,25,8),'AWAITING_REPORT','CLOSE_FIELDWORK',None,'vtyt_demo03')]},
'p4':{'title':'DEMO — Bảo trì tháng 09/2026 đang thực hiện','from':'2026-09-01','to':'2026-09-30','created':T(2026,8,25,9),
      'events':[(T(2026,8,25,9),'DRAFT','CREATE',None,'vtyt_demo04'),(T(2026,8,26,10),'SUBMITTED','SUBMIT_PLAN',None,'vtyt_demo04'),(T(2026,8,27,10,5),'APPROVED','RECORD_APPROVAL',None,'bgd_demo02'),(T(2026,9,10,8),'IN_PROGRESS','START_CAMPAIGN',None,'vtyt_demo04')]},
'p5':{'title':'DEMO — Kế hoạch tháng 10/2026 đã duyệt','from':'2026-10-01','to':'2026-10-31','created':T(2026,9,1,9),
      'events':[(T(2026,9,1,9),'DRAFT','CREATE',None,'demo_vtyt'),(T(2026,9,2,10),'SUBMITTED','SUBMIT_PLAN',None,'demo_vtyt'),(T(2026,9,3,10,5),'REVISION_REQUIRED','RECORD_REVISION','Điều chỉnh phạm vi thiết bị','demo_bgd'),(T(2026,9,4,9),'DRAFT','SAVE_REVISION','Đã cập nhật phạm vi demo','demo_vtyt'),(T(2026,9,5,10),'SUBMITTED','RESUBMIT_PLAN',None,'demo_vtyt'),(T(2026,9,6,10,5),'APPROVED','RECORD_APPROVAL',None,'bgd_demo02')]},
'p6':{'title':'DEMO — Kế hoạch tháng 11/2026 chờ duyệt','from':'2026-11-01','to':'2026-11-30','created':T(2026,9,10,9),
      'events':[(T(2026,9,10,9),'DRAFT','CREATE',None,'vtyt_demo02'),(T(2026,9,11,10),'SUBMITTED','SUBMIT_PLAN',None,'vtyt_demo02')]},
'p7':{'title':'DEMO — Kế hoạch tháng 12/2026 cần chỉnh sửa','from':'2026-12-01','to':'2026-12-31','created':T(2026,9,12,9),
      'events':[(T(2026,9,12,9),'DRAFT','CREATE',None,'vtyt_demo03'),(T(2026,9,13,10),'SUBMITTED','SUBMIT_PLAN',None,'vtyt_demo03'),(T(2026,9,14,10,5),'REVISION_REQUIRED','RECORD_REVISION','Cần rà soát lịch thiết bị','demo_bgd')]}}
assert len(P)==8
PLAN_ACTOR={k:v['events'][0][4] for k,v in P.items()}
PLAN_APPROVED={'p1':T(2025,12,22,10,5),'p2':T(2026,3,22,10,5),'p3':T(2026,6,22,10,5),'p4':T(2026,8,27,10,5),'p5':T(2026,9,6,10,5)}
PLAN_WORK={'p1':T(2026,1,10,9),'p2':T(2026,4,10,9),'p3':T(2026,7,4,9),'p4':T(2026,9,12,9)}

# (equipment no., final item state, optional completed-rework mode)
S={
'p0':[(1,'UNDER_CONTRACT',None),(2,'ASSIGNED_EXTERNAL',None)],
'p1':[(4,'COMPLETED','technical'),(6,'COMPLETED','handover'),(11,'COMPLETED',None),(19,'COMPLETED',None),(28,'REPAIR_REQUIRED',None)],
'p2':[(5,'COMPLETED','technical'),(8,'COMPLETED','technical'),(12,'COMPLETED',None),(25,'COMPLETED',None),(33,'REPAIR_REQUIRED',None)],
'p3':[(7,'COMPLETED','technical'),(10,'COMPLETED',None),(14,'COMPLETED',None),(21,'COMPLETED',None),(26,'REPAIR_REQUIRED',None)],
'p4':[(18,'COMPLETED','technical'),(13,'COMPLETED','technical'),(32,'COMPLETED',None),(15,'AWAITING_HANDOVER',None),(28,'AWAITING_TECHNICAL_ACCEPTANCE',None),(35,'IN_MAINTENANCE',None),(33,'REWORK_REQUIRED',None),(4,'REPAIR_REQUIRED',None),(34,'WAITING_VENDOR_APPROVAL',None),(19,'UNDER_CONTRACT',None)],
'p5':[(1,'UNDER_CONTRACT',None),(5,'UNDER_CONTRACT',None),(11,'UNDER_CONTRACT',None),(14,'UNDER_CONTRACT',None),(21,'UNDER_CONTRACT',None),(26,'UNDER_CONTRACT',None),(2,'ASSIGNED_EXTERNAL',None),(6,'ASSIGNED_EXTERNAL',None),(3,'PLANNED',None),(36,'PLANNED',None),(31,'PENDING_PROPOSAL',None),(27,'WAITING_VENDOR_APPROVAL',None)],
'p6':[(9,'PLANNED',None),(16,'PLANNED',None),(23,'PLANNED',None),(30,'PLANNED',None),(37,'PLANNED',None),(38,'PLANNED',None),(39,'PLANNED',None)],
'p7':[(7,'PLANNED',None),(12,'PLANNED',None),(25,'PLANNED',None),(36,'PLANNED',None),(37,'PLANNED',None),(40,'PLANNED',None)]}
assert sum(map(len,S.values()))==52

PLAN_ALLOWED={None:{'DRAFT'},'DRAFT':{'SUBMITTED'},'SUBMITTED':{'APPROVED','REVISION_REQUIRED'},'REVISION_REQUIRED':{'DRAFT'},'APPROVED':{'IN_PROGRESS'},'IN_PROGRESS':{'AWAITING_REPORT'},'AWAITING_REPORT':{'REPORTED'},'REPORTED':{'CLOSED'}}
ITEM_ALLOWED={None:{'PLANNED'},'PLANNED':{'UNDER_CONTRACT','PENDING_PROPOSAL'},'PENDING_PROPOSAL':{'WAITING_VENDOR_APPROVAL'},'WAITING_VENDOR_APPROVAL':{'ASSIGNED_EXTERNAL','PENDING_PROPOSAL'},'UNDER_CONTRACT':{'IN_MAINTENANCE'},'ASSIGNED_EXTERNAL':{'IN_MAINTENANCE'},'IN_MAINTENANCE':{'AWAITING_TECHNICAL_ACCEPTANCE','REPAIR_REQUIRED'},'AWAITING_TECHNICAL_ACCEPTANCE':{'AWAITING_HANDOVER','REWORK_REQUIRED','REPAIR_REQUIRED'},'AWAITING_HANDOVER':{'COMPLETED','REWORK_REQUIRED','REPAIR_REQUIRED'},'REWORK_REQUIRED':{'IN_MAINTENANCE'}}
for pk,p in P.items():
    old=None
    for when,state,action,reason,actor in p['events']:
        assert state in PLAN_ALLOWED.get(old,set()),(pk,old,state)
        if state=='REVISION_REQUIRED': assert reason
        old=state

items=[]; requests=[]; actions=[]; executions=[]; logs=[]; acceptances=[]
def event(it,when,state,action,reason=None,actor='demo_vtyt'):
    old=it['events'][-1][1] if it['events'] else None
    assert state in ITEM_ALLOWED.get(old,set()),(it['plan'],it['n'],old,state)
    assert not it['events'] or when>it['events'][-1][0]
    if state in ('REWORK_REQUIRED','REPAIR_REQUIRED'): assert reason
    it['events'].append((when,state,action,reason,actor))

def req_add(typ,pk,n,submitted,resolved,status,proposed=None,rationale=None,actor='demo_vtyt',outcome=None,comment=None,decider='demo_bgd'):
    r={'type':typ,'plan':pk,'n':n,'submitted':submitted,'resolved':resolved,'status':status,'proposed':proposed,'rationale':rationale,'creator':actor}
    requests.append(r)
    if outcome:
        assert submitted and resolved and submitted<resolved
        actions.append({'request':r,'actor':decider,'outcome':outcome,'comment':comment,'at':resolved})
    return r

# Plan approval rounds, including revision and a still-pending request.
for pk,submitted,resolved,status,outcome,comment,decider in [
('p1',T(2025,12,21,10),T(2025,12,22,10),'DECIDED','APPROVE','Kế hoạch phù hợp','demo_bgd'),
('p2',T(2026,3,21,10),T(2026,3,22,10),'DECIDED','APPROVE','Đồng ý triển khai','bgd_demo02'),
('p3',T(2026,6,21,10),T(2026,6,22,10),'DECIDED','APPROVE','Đồng ý triển khai','demo_bgd'),
('p4',T(2026,8,26,10),T(2026,8,27,10),'DECIDED','APPROVE','Đồng ý triển khai','bgd_demo02'),
('p5',T(2026,9,2,10),T(2026,9,3,10),'DECIDED','REVISION_REQUIRED','Điều chỉnh phạm vi thiết bị','demo_bgd'),
('p5',T(2026,9,5,10),T(2026,9,6,10),'DECIDED','APPROVE','Đã điều chỉnh phù hợp','bgd_demo02'),
('p6',T(2026,9,11,10),None,'PENDING',None,None,None),
('p7',T(2026,9,13,10),T(2026,9,14,10),'DECIDED','REVISION_REQUIRED','Cần rà soát lịch thiết bị','demo_bgd')]:
    req_add('PLAN_APPROVAL',pk,None,submitted,resolved,status,actor=PLAN_ACTOR[pk],outcome=outcome,comment=comment,decider=decider)

# Each item has a real transition path; no invented intermediate states for quotas.
for pk,rows in S.items():
    p=P[pk]
    for idx,(n,target,rework) in enumerate(rows):
        code=EQ[n]['code']; cl=C[n]['class'] if n in C else None
        created=p['created']+timedelta(hours=2,minutes=idx)
        if pk=='p0': created=T(2026,9,1,8,0,10+idx*10)
        it={'plan':pk,'n':n,'code':code,'target':target,'rework':rework,'class':cl,'events':[],
            'route':None,'assigned':None,'coverage':n in C,'index':idx,'planned_date':None}
        event(it,created,'PLANNED','CREATE',actor=PLAN_ACTOR[pk])
        if pk in ('p1','p2','p3','p4'):
            visit=PLAN_WORK[pk]+timedelta(days=idx*(2 if pk!='p4' else 1))
        elif pk=='p0': visit=T(2026,9,10+idx,9)
        else: visit=T(2026,{'p5':10,'p6':11,'p7':12}[pk],8+idx,9)
        it['planned_date']=visit.date().isoformat()
        if target=='PLANNED':
            items.append(it); continue
        if cl not in ('FREE','NOT_FREE'): raise AssertionError(('routing without verified coverage',pk,n,cl))
        if pk=='p0': route_at=T(2026,9,1,8,1)
        else: route_at=PLAN_APPROVED[pk]+timedelta(days=1,minutes=idx*4)
        if cl=='FREE':
            assert target not in ('PENDING_PROPOSAL','WAITING_VENDOR_APPROVAL','ASSIGNED_EXTERNAL')
            it['route']='UNDER_CONTRACT'; it['assigned']=C[n]['provider']
            event(it,route_at,'UNDER_CONTRACT','VERIFY_FREE_COVERAGE',actor=PLAN_ACTOR[pk])
        else:
            assert target not in ('UNDER_CONTRACT',)
            event(it,route_at,'PENDING_PROPOSAL','CLASSIFY_NOT_FREE',actor=PLAN_ACTOR[pk])
            ext_provider=providers[1] if pk=='p0' else providers[2+(n%5)]
            if target=='PENDING_PROPOSAL':
                req_add('VENDOR_SELECTION',pk,n,None,None,'DRAFT',proposed=ext_provider,
                        rationale='Đề xuất nhà cung cấp mô phỏng đang soạn',actor=PLAN_ACTOR[pk])
            else:
                submitted=(T(2026,9,1,8,2) if pk=='p0' else route_at+timedelta(hours=1))
                event(it,submitted+timedelta(seconds=1),'WAITING_VENDOR_APPROVAL','SUBMIT_VENDOR',actor=PLAN_ACTOR[pk])
                if target=='WAITING_VENDOR_APPROVAL':
                    req_add('VENDOR_SELECTION',pk,n,submitted,None,'PENDING',proposed=ext_provider,
                            rationale='Đề xuất bảo trì ngoài hợp đồng cho thiết bị demo',actor=PLAN_ACTOR[pk])
                else:
                    decided=(T(2026,9,1,8,3) if pk=='p0' else submitted+timedelta(days=1))
                    req_add('VENDOR_SELECTION',pk,n,submitted,decided,'DECIDED',proposed=ext_provider,
                            rationale='Đối tác được chọn theo năng lực mô phỏng và thời gian đáp ứng',
                            actor=PLAN_ACTOR[pk],outcome='APPROVE',comment='Đồng ý chọn đơn vị demo',
                            decider='demo_bgd' if n%2==0 else 'bgd_demo02')
                    it['route']='EXTERNAL_APPROVED'; it['assigned']=ext_provider
                    event(it,decided+timedelta(minutes=1),'ASSIGNED_EXTERNAL','RECORD_VENDOR_APPROVAL',actor=PLAN_ACTOR[pk])
        if pk=='p0' or target in ('UNDER_CONTRACT','ASSIGNED_EXTERNAL','PENDING_PROPOSAL','WAITING_VENDOR_APPROVAL'):
            assert it['events'][-1][1]==target,(pk,n,target,it['events'][-1][1])
            items.append(it); continue
        start=visit
        if target=='COMPLETED' and rework:
            # First failed attempt is preserved. The second is a separate numbered execution.
            event(it,start,'IN_MAINTENANCE','START_ATTEMPT',actor=PLAN_ACTOR[pk])
            end=start+timedelta(hours=3)
            executions.append({'it':it,'no':1,'start':start,'end':end,'provider':it['assigned'],'actor':PLAN_ACTOR[pk],'note':'Lần đầu cần xử lý lại'})
            event(it,end+timedelta(minutes=1),'AWAITING_TECHNICAL_ACCEPTANCE','FINISH_WORK',actor=PLAN_ACTOR[pk])
            if rework=='technical':
                acceptances.append({'it':it,'no':1,'type':'TECHNICAL_ACCEPTANCE','result':'FAIL','at':end+timedelta(minutes=30),'conclusion':'Kiểm tra kỹ thuật chưa đạt; cần xử lý lại','actor':PLAN_ACTOR[pk]})
                event(it,end+timedelta(minutes=31),'REWORK_REQUIRED','TECHNICAL_FAIL','Kết quả kỹ thuật chưa đạt',PLAN_ACTOR[pk])
            else:
                acceptances.append({'it':it,'no':1,'type':'TECHNICAL_ACCEPTANCE','result':'PASS','at':end+timedelta(minutes=30),'conclusion':'Kiểm tra kỹ thuật đạt; chờ bàn giao','actor':PLAN_ACTOR[pk]})
                event(it,end+timedelta(minutes=31),'AWAITING_HANDOVER','TECHNICAL_PASS',actor=PLAN_ACTOR[pk])
                acceptances.append({'it':it,'no':1,'type':'HANDOVER_ACCEPTANCE','result':'FAIL','at':end+timedelta(days=1),'conclusion':'Khoa/Phòng chưa chấp nhận bàn giao; cần xử lý lại','actor':PLAN_ACTOR[pk]})
                event(it,end+timedelta(days=1,minutes=1),'REWORK_REQUIRED','HANDOVER_FAIL','Khoa/Phòng yêu cầu xử lý lại',PLAN_ACTOR[pk])
            start=start+timedelta(days=2)
            attempt=2
        else: attempt=1
        event(it,start,'IN_MAINTENANCE','START_ATTEMPT',actor=PLAN_ACTOR[pk])
        end=None if target=='IN_MAINTENANCE' else start+timedelta(hours=3)
        executions.append({'it':it,'no':attempt,'start':start,'end':end,'provider':it['assigned'],'actor':PLAN_ACTOR[pk],
                           'note':'Đang kiểm tra' if end is None else ('Phát hiện hư hỏng cần chuyển sửa chữa' if target=='REPAIR_REQUIRED' else 'Đã hoàn tất công việc kỹ thuật')})
        if target=='IN_MAINTENANCE':
            items.append(it); continue
        if target=='REPAIR_REQUIRED':
            event(it,end+timedelta(minutes=1),'REPAIR_REQUIRED','HAND_OFF_REPAIR','Phát hiện hư hỏng ngoài phạm vi bảo trì V1',PLAN_ACTOR[pk])
            items.append(it); continue
        event(it,end+timedelta(minutes=1),'AWAITING_TECHNICAL_ACCEPTANCE','FINISH_WORK',actor=PLAN_ACTOR[pk])
        if target=='AWAITING_TECHNICAL_ACCEPTANCE':
            items.append(it); continue
        if target=='REWORK_REQUIRED':
            acceptances.append({'it':it,'no':attempt,'type':'TECHNICAL_ACCEPTANCE','result':'FAIL','at':end+timedelta(minutes=30),'conclusion':'Kiểm tra kỹ thuật chưa đạt; chờ xử lý lại','actor':PLAN_ACTOR[pk]})
            event(it,end+timedelta(minutes=31),'REWORK_REQUIRED','TECHNICAL_FAIL','Kết quả kỹ thuật chưa đạt',PLAN_ACTOR[pk])
            items.append(it); continue
        acceptances.append({'it':it,'no':attempt,'type':'TECHNICAL_ACCEPTANCE','result':'PASS','at':end+timedelta(minutes=30),'conclusion':'Kiểm tra kỹ thuật đạt; đủ điều kiện bàn giao','actor':PLAN_ACTOR[pk]})
        event(it,end+timedelta(minutes=31),'AWAITING_HANDOVER','TECHNICAL_PASS',actor=PLAN_ACTOR[pk])
        if target=='AWAITING_HANDOVER':
            items.append(it); continue
        assert target=='COMPLETED',(pk,n,target)
        acceptances.append({'it':it,'no':attempt,'type':'HANDOVER_ACCEPTANCE','result':'PASS','at':end+timedelta(days=1),'conclusion':'Khoa/Phòng và VTYT xác nhận thiết bị hoạt động sau bảo trì','actor':PLAN_ACTOR[pk]})
        event(it,end+timedelta(days=1,minutes=1),'COMPLETED','HANDOVER_PASS',actor=PLAN_ACTOR[pk])
        items.append(it)

for x in executions:
    it=x['it']; start=x['start']; number=x['no']; n=it['n']
    steps=[('Kiểm tra ngoại quan và tình trạng phụ kiện',None),('Vệ sinh, kiểm tra nguồn và đầu nối',None),('Kiểm tra chức năng và tín hiệu cảnh báo',None)]
    if 'Máy thở' in EQ[n]['name']: steps[2]=('Kiểm tra khởi động và cảnh báo của máy thở',None)
    elif 'Máy xét nghiệm' in EQ[n]['name']: steps[2]=('Kiểm tra quy trình khởi động và trạng thái máy xét nghiệm',None)
    elif 'Máy siêu âm' in EQ[n]['name']: steps[2]=('Kiểm tra đầu dò, cáp kết nối và hiển thị',None)
    elif 'Máy sốc điện' in EQ[n]['name']: steps[2]=('Kiểm tra pin, điện cực và tự kiểm tra thiết bị',None)
    if x['note']=='Phát hiện hư hỏng cần chuyển sửa chữa':
        steps[2]=('Phát hiện bất thường khi kiểm tra chức năng','Bất thường kỹ thuật; chuyển quy trình sửa chữa V2')
    elif number==1 and it['rework']:
        steps[2]=('Ghi nhận hạng mục cần kiểm tra lại',None)
    for offset,(work,damage) in zip((15,60,120),steps):
        logs.append({'x':x,'at':start+timedelta(minutes=offset),'work':work,'damage':damage,'actor':x['actor']})

assert len(items)==52
assert len(requests)==19,(len(requests),Counter(r['type'] for r in requests))
assert len(actions)==15,len(actions)
assert len(executions)==30,len(executions)
assert len(logs)==90,len(logs)
assert len(acceptances)==40,len(acceptances)
assert len({(it['plan'],it['n']) for it in items})==len(items)
for it in items:
    assert it['events'][-1][1]==it['target'],(it['plan'],it['n'],it['target'],it['events'][-1][1])
    if it['route']=='UNDER_CONTRACT': assert C[it['n']]['class']=='FREE' and it['assigned']==C[it['n']]['provider']
    if it['route']=='EXTERNAL_APPROVED': assert C[it['n']]['class']=='NOT_FREE'
    if it['target'] in ('COMPLETED','REPAIR_REQUIRED') and it['plan'] in ('p1','p2','p3'):
        assert it['events'][-1][0]<next(t for t,s,*_ in P[it['plan']]['events'] if s=='AWAITING_REPORT')

# 01: master/reference.
sec=['-- Hospital-style department names are generic; all entities/ownership are synthetic.',
     batch('department',['code','name','active'],[(code,name,True) for code,name in depts]),
     '-- All provider organizations are fictional demo labels; no actual contract is implied.',
     batch('service_provider',['code','name','contact_details','active'],[(f'DEMO_PROVIDER_{i + 1:02d}',name,'Liên hệ giả lập; không dùng để liên hệ thực tế',True) for i,name in enumerate(providers)]),
     '-- Bcrypt hashes came from discarded random inputs; no login password is available.',
     batch('user_account',['department_id','role_code','username','password_hash','display_name','active'],
           [(dept(d) if d else None,role,username,hashes[i],label,True) for i,(username,role,d,label) in enumerate(users)]),
     '-- Public model labels are reference-inspired; asset identity and department are synthetic.',
     batch('equipment',['department_id','equipment_code','name','serial_number','model','technical_spec','active'],
           [(dept(e['dept']),e['code'],e['name'],f'SYN-SN-{int(e["code"][-3:]):04d}',e['model'],None,True) for e in E])]
write('01_master_reference.sql',sec)

# 02: coverage, one row per selected equipment; UNKNOWN stays unverified.
cover_rows=[]
for n,c in C.items():
    free=c['class']=='FREE'; verified=c['verified'] is not None
    cover_rows.append((equipment(EQ[n]['code']),provider(c['provider']) if c['provider'] else None,
                       f'SYN-CONTRACT-2026-{n:03d}' if free else None,
                       'Điều khoản bảo trì giả lập cho dữ liệu demo' if free else None,
                       D(c['from']) if c['from'] else None,D(c['to']) if c['to'] else None,
                       c['class'],user('demo_vtyt') if verified else None,TS(c['verified']) if verified else None,
                       ('Xác minh bảo trì miễn phí theo hợp đồng giả lập' if free else 'Xác minh không thuộc diện miễn phí; cần duyệt đơn vị ngoài') if verified else None))
write('02_equipment_coverage.sql',['-- FREE/NOT_FREE are verified synthetic decisions; UNKNOWN is intentionally unrouted.',
      batch('maintenance_coverage',['equipment_id','provider_id','contract_reference','coverage_scope','effective_from','effective_to','classification','verified_by_user_id','verified_at','basis_note'],cover_rows)])

# 03: plans/items, current state aligned with later evidence; version equals transition count.
plan_rows=[]
for pk,p in P.items():
    plan_rows.append((p['title'],D(p['from']),D(p['to']),p['events'][-1][1],user(PLAN_ACTOR[pk]),len(p['events'])-1,TS(p['created'])))
item_rows=[]
for it in items:
    n=it['n']; p=P[it['plan']]
    item_rows.append((plan(p['title']),equipment(it['code']),dept(EQ[n]['dept']),D(it['planned_date']),it['target'],
                      provider(it['assigned']) if it['assigned'] else None,it['route'],coverage(it['code']) if it['coverage'] else None,len(it['events'])-1))
write('03_plans_and_items.sql',['-- Plan current status and version reflect their exact history in file 06.',
      batch('maintenance_plan',['title','period_start','period_end','status','created_by_user_id','version','created_at'],plan_rows),
      '-- One equipment appears at most once within each plan; repeats across plans support UC12.',
      batch('maintenance_plan_item',['plan_id','equipment_id','department_id_at_plan','planned_date','status','assigned_provider_id','assignment_route','coverage_id','version'],item_rows)])

# 04: approvals/actions. Request identity is resolved by subject + submitted timestamp.
def request_ref(r):
    subject=f'plan_id={plan(P[r["plan"]]["title"])}' if r['type']=='PLAN_APPROVAL' else f'plan_item_id={item_ref(P[r["plan"]]["title"],EQ[r["n"]]["code"])}'
    submitted=f'submitted_at={q(TS(r["submitted"]))}' if r['submitted'] else 'submitted_at IS NULL'
    return Raw(f'(SELECT id FROM approval_request WHERE request_type={q(r["type"])} AND {subject} AND {submitted})')
request_rows=[]
for r in requests:
    request_rows.append((r['type'],plan(P[r['plan']]['title']) if r['type']=='PLAN_APPROVAL' else None,
                         item_ref(P[r['plan']]['title'],EQ[r['n']]['code']) if r['type']=='VENDOR_SELECTION' else None,
                         provider(r['proposed']) if r['proposed'] else None,r['rationale'],
                         'Đã xem xét điều kiện mua sắm trong dữ liệu demo' if r['type']=='VENDOR_SELECTION' else None,
                         r['status'],user(r['creator']),TS(r['submitted']) if r['submitted'] else None,
                         TS(r['resolved']) if r['resolved'] else None))
action_rows=[(request_ref(a['request']),user(a['actor']),a['outcome'],a['comment'],TS(a['at'])) for a in actions]
write('04_approvals.sql',['-- PLAN_APPROVAL and VENDOR_SELECTION have separate typed targets and chronological rounds.',
      batch('approval_request',['request_type','plan_id','plan_item_id','proposed_provider_id','rationale','warranty_impact_note','status','created_by_user_id','submitted_at','resolved_at'],request_rows),
      '-- Every DECIDED request has exactly one director action; PENDING/DRAFT have none.',
      batch('approval_action',['request_id','actor_user_id','outcome','comment','action_at'],action_rows)])

# 05: numbered work attempts, 3 meaningful logs each, typed acceptance.
execution_rows=[]
for x in executions:
    it=x['it']; execution_rows.append((item_ref(P[it['plan']]['title'],it['code']),provider(x['provider']),user(x['actor']),x['no'],TS(x['start']),TS(x['end']) if x['end'] else None,x['note']))
log_rows=[]
for l in logs:
    x=l['x']; it=x['it']; log_rows.append((exec_ref(P[it['plan']]['title'],it['code'],x['no']),user(l['actor']),TS(l['at']),l['work'],l['damage']))
accept_rows=[]
for a in acceptances:
    it=a['it']; signed=a['type']=='HANDOVER_ACCEPTANCE' and a['result']=='PASS'
    sign_time=a['at']+timedelta(minutes=2)
    accept_rows.append((exec_ref(P[it['plan']]['title'],it['code'],a['no']),a['type'],a['result'],TS(a['at']),a['conclusion'],user(a['actor']),
                        user(signer_by_dept[EQ[it['n']]['dept']]) if signed else None,TS(sign_time) if signed else None,
                        user(a['actor']) if signed else None,TS(sign_time) if signed else None))
write('05_execution_and_acceptance.sql',['-- Rework uses another attempt_no; failed assessments remain attached to old attempts.',
      batch('maintenance_execution',['plan_item_id','provider_id','started_by_user_id','attempt_no','started_at','ended_at','result_note'],execution_rows),
      '-- Three concise event notes per attempt; damage_note is present for repair hand-off.',
      batch('maintenance_progress_log',['execution_id','recorded_by_user_id','event_at','work_note','damage_note'],log_rows),
      '-- Successful handover uses scoped department and VTYT users with paired timestamps.',
      batch('acceptance_record',['execution_id','acceptance_type','result','observed_at','conclusion','recorded_by_user_id','department_confirmed_by_user_id','department_confirmed_at','vtyt_confirmed_by_user_id','vtyt_confirmed_at'],accept_rows)])

# 06: reports and complete transition history.
report_specs=[
('p1','FINAL','DEMO-RPT-2026-01','2026-03-20',T(2026,3,20,15),'Đã kiểm tra, vệ sinh và nghiệm thu thiết bị hoàn tất.','Bốn hạng mục hoàn tất và bàn giao.','Một thiết bị chuyển sửa chữa V2.','Phát hiện bất thường ngoài phạm vi bảo trì.','Theo dõi hồ sơ sửa chữa riêng.','Bàn giao thông tin hư hỏng cho giai đoạn sau.','Tiếp tục theo dõi định kỳ.'),
('p2','FINAL','DEMO-RPT-2026-02','2026-06-20',T(2026,6,20,15),'Đã hoàn thành các lượt bảo trì trong kế hoạch.','Bốn hạng mục hoàn tất, có nghiệm thu và bàn giao.','Một hạng mục cần sửa chữa V2.','Lỗi phát hiện trong quá trình kiểm tra.','Chuyển xử lý sửa chữa theo quy trình khác.','Giữ lịch sử bảo trì và nguyên nhân.','Rà soát thiết bị ở đợt sau.'),
('p3','DRAFT','DEMO-RPT-2026-03','2026-07-27',None,'Tổng hợp công việc bảo trì tháng 07.','Bốn hạng mục đã hoàn tất.','Một hạng mục chuyển sửa chữa V2.','Bất thường ngoài phạm vi bảo trì.','Hoàn thiện báo cáo trình duyệt.','Giữ thông tin hand-off.','Theo dõi đợt kế tiếp.'),
('p4','DRAFT','DEMO-RPT-2026-04','2026-09-24',None,'Bản nháp kết quả đang thực hiện.','Ba hạng mục đã hoàn tất.','Các hạng mục còn đang xử lý hoặc chờ phê duyệt.','Một trường hợp cần sửa chữa V2.','Tiếp tục nghiệm thu và bàn giao.','Theo dõi hạng mục cần làm lại.','Cập nhật sau khi hoàn thành đợt.')]
report_rows=[]
for pk,status,number,date,finalized,work,achieved,not_achieved,causes,next_work,resolutions,recommendations in report_specs:
    report_rows.append((plan(P[pk]['title']),user(PLAN_ACTOR[pk]),number,D(date),work,achieved,not_achieved,causes,next_work,resolutions,recommendations,status,TS(finalized) if finalized else None))
plan_history=[]
for pk,p in P.items():
    old=None
    for when,state,action,reason,actor in p['events']:
        plan_history.append((plan(p['title']),None,user(actor),old,state,action,reason,TS(when)))
        old=state
item_history=[]
for it in items:
    old=None
    for when,state,action,reason,actor in it['events']:
        item_history.append((None,item_ref(P[it['plan']]['title'],it['code']),user(actor),old,state,action,reason,TS(when)))
        old=state
assert len(plan_history)+len(item_history)>120 # Complete history has precedence over target range.
write('06_reports_and_history.sql',['-- Reports summarize actual final item results; REPAIR_REQUIRED is never counted as COMPLETED.',
      batch('maintenance_report',['plan_id','created_by_user_id','report_number','report_date','work_done','achieved','not_achieved','causes','next_work','resolutions','recommendations','status','finalized_at'],report_rows),
      '-- Every plan and item state transition, including creation, is retained as typed history.',
      batch('status_history',['plan_id','plan_item_id','actor_user_id','old_state','new_state','action','reason','action_timestamp'],plan_history+item_history)])

print('generated:',len(depts),'departments,',len(users),'users,',len(E),'equipment,',len(providers),'providers,',len(C),'coverage,',len(P),'plans,',len(items),'items,',len(requests),'requests,',len(actions),'actions,',len(executions),'executions,',len(logs),'logs,',len(acceptances),'acceptances,',len(report_rows),'reports,',len(plan_history)+len(item_history),'history')
