import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { NotificationBell } from './NotificationBell'
import { notificationsApi, notificationsChanged } from '../api/notificationsApi'
import type { UserNotification } from '../types/workflow'
vi.mock('../api/notificationsApi',()=>({notificationsChanged:'maintenance:notifications-changed',notificationsApi:{unread:vi.fn(),list:vi.fn(),read:vi.fn()}}))
const row:UserNotification={id:12,notificationType:'PLAN_SUBMITTED',title:'Kế hoạch cần phê duyệt',message:'Phòng VTYT đã gửi kế hoạch.',targetUrl:'/approvals/12',createdAt:'2026-10-05T00:00:00Z',readAt:null}
function page(){return render(<MemoryRouter><button>Phần khác</button><Routes><Route path="/" element={<NotificationBell/>}/><Route path="/approvals/12" element={<p>Chi tiết phê duyệt</p>}/><Route path="/notifications" element={<p>Tất cả thông báo</p>}/></Routes></MemoryRouter>)}
beforeEach(()=>{vi.resetAllMocks();vi.mocked(notificationsApi.unread).mockResolvedValue({count:1});vi.mocked(notificationsApi.list).mockResolvedValue({content:[row],page:0,size:5,totalElements:1,totalPages:1,last:true});vi.mocked(notificationsApi.read).mockResolvedValue({...row,readAt:'2026-10-05T01:00:00Z'})})
afterEach(()=>{cleanup();vi.useRealTimers()})
it('shows the unread bell state and loads the preview only when opened',async()=>{const {container}=page();const trigger=await screen.findByRole('button',{name:'Thông báo: 1 chưa đọc'});expect(container.querySelector('.notification-bell.has-unread')).toBeTruthy();expect(notificationsApi.list).not.toHaveBeenCalled();fireEvent.click(trigger);expect(await screen.findByText(row.title)).toBeTruthy();expect(notificationsApi.list).toHaveBeenCalledWith(0,5);expect(trigger.getAttribute('aria-expanded')).toBe('true');expect(screen.getByRole('region',{name:'Thông báo mới'}).id).toBe(trigger.getAttribute('aria-controls'))})
it('closes with Escape, restores trigger focus, and closes on an outside pointer',async()=>{page();const trigger=await screen.findByRole('button',{name:'Thông báo: 1 chưa đọc'});fireEvent.click(trigger);await screen.findByText(row.title);fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('region',{name:'Thông báo mới'})).toBeNull();expect(document.activeElement).toBe(trigger);fireEvent.click(trigger);await screen.findByText(row.title);fireEvent.pointerDown(screen.getByRole('button',{name:'Phần khác'}));expect(screen.queryByRole('region',{name:'Thông báo mới'})).toBeNull()})
it('keeps the existing read-before-navigation workflow',async()=>{page();fireEvent.click(await screen.findByRole('button',{name:'Thông báo: 1 chưa đọc'}));fireEvent.click(await screen.findByRole('button',{name:/Kế hoạch cần phê duyệt/}));expect(await screen.findByText('Chi tiết phê duyệt')).toBeTruthy();expect(notificationsApi.read).toHaveBeenCalledWith(12)})
it('updates the unread state after the existing notifications event',async()=>{const {container}=page();await screen.findByRole('button',{name:'Thông báo: 1 chưa đọc'});vi.mocked(notificationsApi.unread).mockResolvedValue({count:0});fireEvent(window,new Event(notificationsChanged));await screen.findByRole('button',{name:'Thông báo: 0 chưa đọc'});expect(container.querySelector('.has-unread')).toBeNull()})
it('shows loading feedback and allows retrying a failed preview',async()=>{vi.mocked(notificationsApi.list).mockRejectedValueOnce(new Error('Network'));page();fireEvent.click(await screen.findByRole('button',{name:'Thông báo: 1 chưa đọc'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'Thử lại'}));expect(await screen.findByText(row.title)).toBeTruthy();expect(notificationsApi.list).toHaveBeenCalledTimes(2)})
it('keeps the preview open on a read failure and prevents navigating',async()=>{vi.mocked(notificationsApi.read).mockRejectedValue(new Error('Network'));page();fireEvent.click(await screen.findByRole('button',{name:'Thông báo: 1 chưa đọc'}));fireEvent.click(await screen.findByRole('button',{name:/Kế hoạch cần phê duyệt/}));expect(await screen.findByRole('alert')).toBeTruthy();expect(screen.queryByText('Chi tiết phê duyệt')).toBeNull();await waitFor(()=>expect(screen.getByRole('region',{name:'Thông báo mới'})).toBeTruthy())})
