import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { apiRequest } from '../api/client'
import { WorkflowError } from './WorkflowFeedback'
interface Schedule { maintenance_enabled: boolean; maintenance_interval_value: number | null; maintenance_interval_unit: string | null; commissioning_date: string | null }
export function ScheduleEditor({ equipmentId, onClose }: { equipmentId: number; onClose: () => void }) {
 const [enabled, setEnabled] = useState(false); const [value, setValue] = useState(''); const [unit, setUnit] = useState('MONTH'); const [base, setBase] = useState(''); const [error, setError] = useState<unknown>(null); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false)
 useEffect(() => { let active = true; apiRequest<Schedule>(`/api/equipment/${equipmentId}/schedule`).then(s => { if (active) { setEnabled(s.maintenance_enabled); setValue(String(s.maintenance_interval_value || '')); setUnit(s.maintenance_interval_unit || 'MONTH'); setBase(s.commissioning_date || ''); setReady(true) } }).catch(e => { if (active) setError(e) }); return () => { active = false } }, [equipmentId])
 async function save(e: FormEvent) { e.preventDefault(); setBusy(true); try { await apiRequest(`/api/equipment/${equipmentId}/schedule`, { method: 'PUT', body: { enabled, intervalValue: value ? Number(value) : null, intervalUnit: value ? unit : null, commissioningDate: base || null } }); onClose() } catch (e) { setError(e) } finally { setBusy(false) } }
 return <section className="panel business-panel" role="dialog" aria-label="Cấu hình bảo trì định kỳ"><h2>Cấu hình bảo trì định kỳ</h2><p>Ngày đưa vào sử dụng chỉ dùng khi chưa có lịch sử bảo trì hoàn tất. Để trống nếu chưa có hồ sơ xác nhận.</p><WorkflowError error={error} /><form onSubmit={e => void save(e)}><fieldset disabled={!ready || busy}><label><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} />Bật bảo trì định kỳ</label><div className="form-grid"><label>Giá trị chu kỳ<input type="number" min="1" max="1200" required={enabled} value={value} onChange={e => setValue(e.target.value)} /></label><label>Đơn vị chu kỳ<select value={unit} onChange={e => setUnit(e.target.value)}><option value="DAY">Ngày</option><option value="MONTH">Tháng</option><option value="YEAR">Năm</option></select></label><label>Ngày đưa vào sử dụng<input type="date" value={base} onChange={e => setBase(e.target.value)} /></label></div><button className="button primary" type="submit">Lưu chu kỳ</button></fieldset><button type="button" className="button secondary" onClick={onClose}>Đóng</button></form></section>
}
