import { Link } from 'react-router'
import { DashboardHeader, DashboardSection, DonutChart, EmptyDashboardState, MetricCard, QuickActions } from '../../components/DashboardComponents'
import { UiIcon } from '../../components/UiIcon'
import type { AdminDashboardData } from '../../types/dashboard'
import { roleLabels } from '../../utils/roleLabels'
import { roles } from '../../types/auth'
export function AdminDashboard({ data }: { data: AdminDashboardData }) {
 const s=data.summary;const attention=data.quality.filter(q=>q.count>0);const total=data.accountsByRole.reduce((n,r)=>n+r.count,0);const colors=['#219985','#428eb4','#e5a03e','#8b7cb5']
 const segments=roles.map((role,i)=>({label:roleLabels[role],value:data.accountsByRole.find(r=>r.role===role)?.count??0,color:colors[i]}))
 return <><DashboardHeader title="Tổng quan quản trị hệ thống" context="Tài khoản, danh mục và mức độ đầy đủ của dữ liệu." generatedAt={data.generatedAt} action={{label:'Quản lý tài khoản',href:'/admin/accounts'}}/><QuickActions actions={data.quickActions}/>
 <div className="dashboard-metrics"><MetricCard label="Tài khoản hoạt động" value={s.activeAccounts} href="/admin/accounts?active=true" tone="success" icon="users"/><MetricCard label="Tài khoản không hoạt động" value={s.inactiveAccounts} href="/admin/accounts?active=false" icon="shield"/><MetricCard label="Khoa/Phòng" value={s.departments} href="/admin/catalogs/departments" icon="building"/><MetricCard label="Công ty / nhà cung cấp" value={s.providers} href="/admin/catalogs/providers" icon="briefcase"/><MetricCard label="Hợp đồng" value={s.contracts} href="/contracts" icon="contract"/></div>
 <DashboardSection title="Dữ liệu cần chú ý" className={`dashboard-attention${attention.length?' has-items':''}`} count={attention.length}>{attention.length?<ul className="dashboard-records dashboard-quality-list">{attention.map(q=><li key={q.label}><span className="dashboard-attention-icon"><UiIcon name="alert"/></span><div><strong>{q.label}</strong></div><Link className="dashboard-quality-count" to={q.href}>{q.count}<span aria-hidden="true">→</span></Link></li>)}</ul>:<EmptyDashboardState>Không phát hiện hồ sơ cần bổ sung trong các kiểm tra hiện có.</EmptyDashboardState>}</DashboardSection>
 <div className="dashboard-two-columns"><DashboardSection title="Tài khoản theo vai trò" description={`${total} tài khoản · gồm cả tài khoản không hoạt động`}><div className="dashboard-chart-layout dashboard-role-chart"><DonutChart segments={segments} label="tài khoản"/><ul className="dashboard-role-counts">{roles.map((role,i)=><li key={role}><Link to={`/admin/accounts?role=${role}`}><i style={{background:colors[i]}}/><span>{roleLabels[role]}</span><strong>{segments[i].value}</strong><span aria-hidden="true">↗</span></Link></li>)}</ul></div></DashboardSection><DashboardSection title="Danh mục hệ thống" description="Truy cập các hồ sơ quản lý"><div className="dashboard-admin-catalogs"><Link to="/admin/equipment"><UiIcon name="equipment"/><span>Hồ sơ thiết bị & lịch bảo trì</span><span aria-hidden="true">→</span></Link><Link to="/admin/catalogs/departments"><UiIcon name="building"/><span>Khoa / Phòng</span><strong>{s.departments}</strong><span aria-hidden="true">→</span></Link><Link to="/admin/catalogs/providers"><UiIcon name="briefcase"/><span>Đơn vị bảo trì</span><strong>{s.providers}</strong><span aria-hidden="true">→</span></Link><Link to="/contracts"><UiIcon name="contract"/><span>Hợp đồng bảo trì</span><strong>{s.contracts}</strong><span aria-hidden="true">→</span></Link></div></DashboardSection></div></>
}
