import { Link } from 'react-router'
import { DashboardHeader, DashboardSection, EmptyDashboardState, MetricCard, QuickActions } from '../../components/DashboardComponents'
import type { AdminDashboardData } from '../../types/dashboard'
import { roleLabels } from '../../utils/roleLabels'
import { roles } from '../../types/auth'
export function AdminDashboard({ data }: { data: AdminDashboardData }) {
 const s=data.summary; const attention=data.quality.filter(q=>q.count>0); const total=data.accountsByRole.reduce((n,r)=>n+r.count,0)
 return <><DashboardHeader title="Tổng quan quản trị hệ thống" context="Quản lý tài khoản, danh mục và kiểm tra mức độ đầy đủ của hồ sơ." generatedAt={data.generatedAt} action={{label:'Quản lý tài khoản',href:'/admin/accounts'}} />
 <DashboardSection title="Dữ liệu cần chú ý" className="dashboard-attention">{attention.length?<ul className="dashboard-records">{attention.map(q=><li key={q.label}><div><strong>{q.label}</strong><p>Cần kiểm tra tại danh mục quản lý liên quan.</p></div><Link className="dashboard-quality-count" to={q.href}>{q.count} <span aria-hidden="true">→</span></Link></li>)}</ul>:<EmptyDashboardState>Không phát hiện hồ sơ cần bổ sung trong các kiểm tra hiện có.</EmptyDashboardState>}</DashboardSection>
 <div className="dashboard-metrics"><MetricCard label="Tài khoản hoạt động" value={s.activeAccounts} href="/admin/accounts?active=true" tone="success" /><MetricCard label="Tài khoản không hoạt động" value={s.inactiveAccounts} href="/admin/accounts?active=false" /><MetricCard label="Khoa/Phòng" value={s.departments} href="/admin/catalogs/departments" /><MetricCard label="Công ty / nhà cung cấp" value={s.providers} href="/admin/catalogs/providers" /><MetricCard label="Hợp đồng" value={s.contracts} href="/contracts" /></div>
 <div className="dashboard-two-columns"><DashboardSection title="Tài khoản theo vai trò" description={`${total} tài khoản trong hệ thống; gồm cả tài khoản không hoạt động.`}><ul className="dashboard-role-counts">{roles.map(role=>{const count=data.accountsByRole.find(r=>r.role===role)?.count??0;return <li key={role}><Link to={`/admin/accounts?role=${role}`}><span>{roleLabels[role]}</span><strong>{count}</strong></Link><div className="dashboard-role-bar"><span style={{width:`${total?count/total*100:0}%`}} /></div></li>})}</ul></DashboardSection><DashboardSection title="Danh mục hệ thống" description="Kiểm tra đơn vị tổ chức, đối tác và các hồ sơ cấu hình bảo trì."><div className="dashboard-admin-catalogs"><Link to="/admin/equipment">Hồ sơ thiết bị & lịch bảo trì <span>→</span></Link><Link to="/admin/catalogs/departments">Khoa / Phòng <span>{s.departments}</span></Link><Link to="/admin/catalogs/providers">Đơn vị bảo trì <span>{s.providers}</span></Link><Link to="/contracts">Hợp đồng bảo trì <span>{s.contracts}</span></Link></div></DashboardSection></div><QuickActions actions={data.quickActions} /></>
}
