import { Link } from 'react-router'
import { DashboardHeader, DashboardSection, DonutChart, EmptyDashboardState, MetricCard, QuickActions, ReportList } from '../../components/DashboardComponents'
import { StatusBadge } from '../../components/StatusBadge'
import { UiIcon } from '../../components/UiIcon'
import type { BgdDashboardData } from '../../types/dashboard'
import { approvalTypeLabels, dateTime } from '../../utils/workflowLabels'
export function BgdDashboard({ data }: { data: BgdDashboardData }) {
 const s=data.summary;const segments=[{label:'Kế hoạch',value:s.pendingPlans,color:'#219985'}]
 return <><DashboardHeader title="Tổng quan Ban Giám đốc" context="Theo dõi hồ sơ cần quyết định và báo cáo đã nhận." generatedAt={data.generatedAt} action={{label:'Mở hàng chờ phê duyệt',href:'/approvals'}}/><QuickActions actions={data.quickActions}/>
 <div className="dashboard-metrics"><MetricCard label="Chờ phê duyệt" value={s.pendingPlans} href="/approvals" tone={s.pendingPlans?'warning':'neutral'} icon="clock"/><MetricCard label="Đã phê duyệt trong tháng" value={s.approvedThisMonth} href="/dashboard#recent-decisions" tone="success" icon="check"/><MetricCard label="Yêu cầu chỉnh sửa trong tháng" value={s.revisedThisMonth} href="/dashboard#recent-decisions" icon="contract"/><MetricCard label="Báo cáo mới trong tháng" value={s.reportsThisMonth} href="/reports" icon="report"/></div>
 <DashboardSection title="Chờ phê duyệt" className="dashboard-approval-panel" count={s.pendingPlans} action={{label:'Hàng chờ phê duyệt',href:'/approvals'}}><div className="dashboard-approval-layout"><div className="dashboard-approval-summary"><DonutChart segments={segments} label="hồ sơ"/><div className="dashboard-approval-filters"><Link to="/approvals?requestType=PLAN_APPROVAL"><i style={{background:segments[0].color}}/><span>Kế hoạch chờ phê duyệt</span><strong>{s.pendingPlans}</strong><span aria-hidden="true">↗</span></Link></div></div>{data.pending.length?<ul className="dashboard-records">{data.pending.map(r=><li key={r.id}><span className="dashboard-record-icon"><UiIcon name={r.type==='PLAN_APPROVAL'?'calendar':'briefcase'}/></span><div><Link className="table-link" to={`/approvals/${r.id}`}>{r.title}{r.equipmentCode&&` · ${r.equipmentCode}`}</Link><p>{approvalTypeLabels[r.type]} · {r.sender} · {dateTime(r.at)}</p></div><Link className="button secondary compact" to={`/approvals/${r.id}`}>Xem →</Link></li>)}</ul>:<EmptyDashboardState>Không có hồ sơ nào đang chờ phê duyệt.</EmptyDashboardState>}</div></DashboardSection>
 <div className="dashboard-two-columns"><div id="recent-decisions"><DashboardSection title="Quyết định gần đây" description="5 quyết định mới nhất">{data.decisions.length?<ul className="dashboard-records">{data.decisions.map(d=><li key={d.requestId}><div><Link className="table-link" to={`/approvals/${d.requestId}`}>{d.title}{d.equipmentCode&&` · ${d.equipmentCode}`}</Link><p>{d.actor} · {dateTime(d.at)}</p>{d.comment&&<p className="dashboard-row-note">{d.comment}</p>}</div><StatusBadge label={d.outcome==='APPROVE'?'Phê duyệt':'Yêu cầu chỉnh sửa'} tone={d.outcome==='APPROVE'?'teal':'amber'}/></li>)}</ul>:<EmptyDashboardState>Chưa có quyết định phê duyệt.</EmptyDashboardState>}</DashboardSection></div><DashboardSection title="Báo cáo bảo trì gần đây" action={{label:'Xem tất cả báo cáo',href:'/reports'}}><ReportList reports={data.reports}/></DashboardSection></div></>
}
