import { Link } from 'react-router'
import { DashboardHeader, DashboardSection, EmptyDashboardState, MetricCard, QuickActions, ReportList } from '../../components/DashboardComponents'
import { StatusBadge } from '../../components/StatusBadge'
import type { BgdDashboardData } from '../../types/dashboard'
import { approvalTypeLabels, dateTime } from '../../utils/workflowLabels'
export function BgdDashboard({ data }: { data: BgdDashboardData }) {
 const s=data.summary
 return <><DashboardHeader title="Tổng quan Ban Giám đốc" context="Các hồ sơ chờ quyết định và báo cáo bảo trì VTYT đã gửi." generatedAt={data.generatedAt} action={{label:'Mở hàng chờ phê duyệt',href:'/approvals'}} />
 <DashboardSection title="Chờ phê duyệt" className="dashboard-attention"><div className="dashboard-pending-grid"><MetricCard label="Kế hoạch chờ phê duyệt" value={s.pendingPlans} href="/approvals?requestType=PLAN_APPROVAL" tone={s.pendingPlans?'warning':'neutral'} /><MetricCard label="Đề xuất đơn vị chờ phê duyệt" value={s.pendingProviders} href="/approvals?requestType=VENDOR_SELECTION" tone={s.pendingProviders?'warning':'neutral'} /></div>{data.pending.length?<ul className="dashboard-records">{data.pending.map(r=><li key={r.id}><div><Link className="table-link" to={`/approvals/${r.id}`}>{r.title}{r.equipmentCode && ` · ${r.equipmentCode}`}</Link><p>{approvalTypeLabels[r.type]} · {r.sender} · {dateTime(r.at)}</p></div><Link className="button secondary compact" to={`/approvals/${r.id}`}>Xem →</Link></li>)}</ul>:<EmptyDashboardState>Không có hồ sơ nào đang chờ phê duyệt.</EmptyDashboardState>}</DashboardSection>
 <div className="dashboard-metrics"><MetricCard label="Chờ phê duyệt" value={s.pendingPlans+s.pendingProviders} href="/approvals" /><MetricCard label="Đã phê duyệt trong tháng" value={s.approvedThisMonth} href="/dashboard#recent-decisions" tone="success" /><MetricCard label="Yêu cầu chỉnh sửa trong tháng" value={s.revisedThisMonth} href="/dashboard#recent-decisions" /><MetricCard label="Báo cáo mới trong tháng" value={s.reportsThisMonth} href="/reports" /></div>
 <div className="dashboard-two-columns"><div id="recent-decisions"><DashboardSection title="Quyết định gần đây" description="5 quyết định mới nhất; số liệu tháng tính theo giờ Việt Nam.">{data.decisions.length?<ul className="dashboard-records">{data.decisions.map(d=><li key={d.requestId}><div><Link className="table-link" to={`/approvals/${d.requestId}`}>{d.title}{d.equipmentCode&&` · ${d.equipmentCode}`}</Link><p>{d.actor} · {dateTime(d.at)}</p>{d.comment&&<p className="dashboard-row-note">{d.comment}</p>}</div><StatusBadge label={d.outcome==='APPROVE'?'Phê duyệt':'Yêu cầu chỉnh sửa'} tone={d.outcome==='APPROVE'?'teal':'amber'} /></li>)}</ul>:<EmptyDashboardState>Chưa có quyết định phê duyệt.</EmptyDashboardState>}</DashboardSection></div><DashboardSection title="Báo cáo bảo trì gần đây" action={{label:'Xem tất cả báo cáo',href:'/reports'}}><ReportList reports={data.reports} /></DashboardSection></div><QuickActions actions={data.quickActions} /></>
}
