import { Link } from 'react-router'
import { AttentionList, ChartLegend, DashboardHeader, DashboardSection, DonutChart, EmptyDashboardState, ItemList, MetricCard, QuickActions, ReportList } from '../../components/DashboardComponents'
import { StatusBadge } from '../../components/StatusBadge'
import { UiIcon } from '../../components/UiIcon'
import type { VtytDashboardData } from '../../types/dashboard'
import { businessDate, planStatusLabels } from '../../utils/workflowLabels'
import { quarterLabels } from '../../api/quarterlyApi'
import type { Quarter } from '../../api/quarterlyApi'
export function VtytDashboard({ data }: { data: VtytDashboardData }) {
 const q=data.currentQuarter;const create=`/plans/new?year=${q.year}&quarter=${q.quarter}`
 const segments=[{label:'Chưa bắt đầu',value:data.progress.notStarted,color:'#c6d5df'},{label:'Đang bảo trì',value:data.progress.inProgress,color:'#428eb4'},{label:'Bảo trì xong',value:data.progress.workDone,color:'#219985'},{label:'Có hỏng hóc',value:data.progress.damaged,color:'#e5a03e'}]
 const total=segments.reduce((n,s)=>n+s.value,0);const covered=q.underContract+q.outsideContract
 const planTarget=q.plan?q.plan.status==='IN_PROGRESS'||q.plan.status==='APPROVED'?`/maintenance-progress/plans/${q.plan.id}`:q.plan.status==='AWAITING_REPORT'||q.plan.status==='REPORTED'?`/plans/${q.plan.id}/report`:`/plans/${q.plan.id}`:create
 return <><DashboardHeader title="Tổng quan Phòng Vật tư Y tế" context="Kế hoạch, tiến độ và kết quả bảo trì trong một góc nhìn." generatedAt={data.generatedAt} action={{label:'Tạo kế hoạch bảo trì',href:create}}/>
 <QuickActions actions={data.quickActions}/>
 <div className="dashboard-metrics"><MetricCard label="Đến lịch quý này" value={data.summary.scheduled} href={planTarget} detail="Thiết bị có lịch bảo trì" icon="calendar"/><MetricCard label="Hợp đồng còn hiệu lực" value={data.summary.activeContracts} href="/contracts" tone="success" icon="contract"/><MetricCard label="Thiết bị đang bảo trì" value={data.summary.maintaining} href="/maintenance-progress?status=IN_PROGRESS" icon="equipment"/><MetricCard label="Chờ nghiệm thu kỹ thuật" value={data.summary.technical} href="/maintenance-progress?status=IN_PROGRESS&itemStatus=AWAITING_TECHNICAL_ACCEPTANCE" tone={data.summary.technical?'warning':'neutral'} icon="check"/><MetricCard label="Kế hoạch chờ báo cáo" value={data.summary.awaitingReport} href="/reports?status=AWAITING_REPORT" tone={data.summary.awaitingReport?'warning':'neutral'} icon="report"/></div>
 <DashboardSection title="Việc cần xử lý" className={`dashboard-attention${data.attention.length?' has-items':''}`} count={data.attention.length}><AttentionList items={data.attention}/></DashboardSection>
 <div className="dashboard-two-columns dashboard-focus-grid"><DashboardSection title="Kế hoạch bảo trì quý hiện tại" className="dashboard-quarter" description={`${quarterLabels[q.quarter as Quarter]} · ${q.year}`}>
 <div className="dashboard-quarter-summary"><div><strong>{q.scheduled}</strong><span>thiết bị có lịch quý</span></div><div className="dashboard-quarter-marker"><UiIcon name="calendar"/><span>{q.quarter}<small>{q.year}</small></span></div></div>
 <div className="dashboard-coverage-bar" aria-label={`${q.underContract} thiết bị theo hợp đồng, ${q.outsideContract} ngoài hợp đồng`}><span style={{width:`${covered?q.underContract/covered*100:0}%`}}/></div>
 <div className="dashboard-quarter-counts"><div><span>Theo hợp đồng</span><strong>{q.underContract}</strong></div><div><span>Ngoài hợp đồng</span><strong>{q.outsideContract}</strong></div><div><span>Đang bảo trì</span><strong>{q.inProgress}</strong></div><div><span>Hoàn thành</span><strong>{q.completed}</strong></div></div>
 <div className="dashboard-quarter-footer"><StatusBadge label={q.plan?planStatusLabels[q.plan.status]:'Chưa có kế hoạch'} tone={q.plan?.status==='REPORTED'?'teal':'neutral'}/><Link className="text-link" to={planTarget}>{q.plan?'Mở kế hoạch quý hiện tại':`Tạo kế hoạch ${quarterLabels[q.quarter as Quarter]} năm ${q.year}`} →</Link></div>{q.plan&&<p className="dashboard-quarter-title">{q.plan.title}</p>}
 </DashboardSection><DashboardSection title="Tiến độ bảo trì" description="Các kế hoạch đã duyệt và đang thực hiện" action={{label:'Theo dõi',href:'/maintenance-progress?status=IN_PROGRESS'}}>
 <div className="dashboard-chart-layout"><DonutChart segments={segments}/><ChartLegend segments={segments}/></div>{!total&&<p className="dashboard-chart-empty">Chưa có kế hoạch đang thực hiện bảo trì.</p>}
 <div className="dashboard-secondary-counts"><span>Chờ nghiệm thu kỹ thuật <strong>{data.progress.technical}</strong></span><span>Chờ bàn giao <strong>{data.progress.handover}</strong></span></div>
 </DashboardSection></div>
 <div className="dashboard-two-columns"><DashboardSection title="Tình trạng hợp đồng" description="Sắp hết hạn trong 30 ngày" action={{label:'Danh sách hợp đồng',href:'/contracts'}}><div className="dashboard-contract-counts"><Link to="/contracts"><i className="success"/><strong>{data.contracts.valid}</strong><span>Còn hiệu lực</span></Link><Link to="/contracts"><i className="warning"/><strong>{data.contracts.expiring}</strong><span>Sắp hết hạn</span></Link><Link to="/contracts"><i className="muted"/><strong>{data.contracts.expired}</strong><span>Đã hết hạn</span></Link></div>{data.expiringContracts.length?<ul className="dashboard-records">{data.expiringContracts.map(c=><li key={c.id}><div><Link className="table-link" to={`/contracts/${c.id}`}>{c.code}</Link><p>{c.provider} · {c.equipmentCount} thiết bị</p></div><StatusBadge label={businessDate(c.endDate)} tone="amber"/></li>)}</ul>:<EmptyDashboardState>Không có hợp đồng sắp hết hạn trong 30 ngày.</EmptyDashboardState>}</DashboardSection><DashboardSection title="Cập nhật gần đây" description="5 cập nhật tiến độ mới nhất"><ItemList items={data.recentProgress} mode="progress" empty="Chưa có cập nhật tiến độ bảo trì."/></DashboardSection></div>
 <DashboardSection title="Báo cáo bảo trì gần đây" action={{label:'Lịch sử bảo trì',href:'/maintenance-history'}}><ReportList reports={data.reports}/></DashboardSection></>
}
