import { Link } from 'react-router'
import { AttentionList, DashboardHeader, DashboardSection, EmptyDashboardState, ItemList, MetricCard, QuickActions, ReportList } from '../../components/DashboardComponents'
import { StatusBadge } from '../../components/StatusBadge'
import type { VtytDashboardData } from '../../types/dashboard'
import { businessDate, planStatusLabels } from '../../utils/workflowLabels'
import { quarterLabels } from '../../api/quarterlyApi'
import type { Quarter } from '../../api/quarterlyApi'
export function VtytDashboard({ data }: { data: VtytDashboardData }) {
 const q = data.currentQuarter; const create = `/plans/new?year=${q.year}&quarter=${q.quarter}`
 const stages = [{ label: 'Chưa bắt đầu', count: data.progress.notStarted, tone: 'neutral' }, { label: 'Đang bảo trì', count: data.progress.inProgress, tone: 'ongoing' }, { label: 'Bảo trì xong', count: data.progress.workDone, tone: 'done' }, { label: 'Có hỏng hóc', count: data.progress.damaged, tone: 'damage' }]
 const total = stages.reduce((n,s) => n+s.count,0)
 const planTarget = q.plan ? q.plan.status === 'IN_PROGRESS' || q.plan.status === 'APPROVED' ? `/maintenance-progress/plans/${q.plan.id}` : q.plan.status === 'AWAITING_REPORT' || q.plan.status === 'REPORTED' ? `/plans/${q.plan.id}/report` : `/plans/${q.plan.id}` : create
 return <><DashboardHeader title="Tổng quan Phòng Vật tư Y tế" context="Ưu tiên việc cần xử lý, chuẩn bị kế hoạch quý và theo dõi kết quả bảo trì." generatedAt={data.generatedAt} action={{ label: 'Tạo kế hoạch bảo trì', href: create }} />
 <DashboardSection title="Việc cần xử lý" className="dashboard-attention" description="Tối đa 5 việc ưu tiên, theo trạng thái xử lý hiện tại."><AttentionList items={data.attention} /></DashboardSection>
 <div className="dashboard-metrics"><MetricCard label="Đến lịch quý này" value={data.summary.scheduled} href={planTarget} detail="Thiết bị có lịch bảo trì" /><MetricCard label="Hợp đồng còn hiệu lực" value={data.summary.activeContracts} href="/contracts" tone="success" /><MetricCard label="Thiết bị đang bảo trì" value={data.summary.maintaining} href="/maintenance-progress?status=IN_PROGRESS" /><MetricCard label="Chờ nghiệm thu kỹ thuật" value={data.summary.technical} href="/maintenance-progress?status=IN_PROGRESS&itemStatus=AWAITING_TECHNICAL_ACCEPTANCE" tone={data.summary.technical ? 'warning' : 'neutral'} /><MetricCard label="Kế hoạch chờ báo cáo" value={data.summary.awaitingReport} href="/reports?status=AWAITING_REPORT" tone={data.summary.awaitingReport ? 'warning' : 'neutral'} /></div>
 <div className="dashboard-two-columns"><DashboardSection title="Kế hoạch bảo trì quý hiện tại" className="dashboard-quarter" description={`${quarterLabels[q.quarter as Quarter]} năm ${q.year}`}>
 <div className="dashboard-quarter-summary"><strong>{q.scheduled}<small>thiết bị có lịch quý</small></strong><StatusBadge label={q.plan ? planStatusLabels[q.plan.status] : 'Chưa có kế hoạch'} tone={q.plan?.status === 'REPORTED' ? 'teal' : 'neutral'} /></div>
 <div className="dashboard-quarter-counts"><div><span>Theo hợp đồng</span><strong>{q.underContract}</strong></div><div><span>Ngoài hợp đồng</span><strong>{q.outsideContract}</strong></div><div><span>Đang bảo trì</span><strong>{q.inProgress}</strong></div><div><span>Hoàn thành</span><strong>{q.completed}</strong></div></div>
 <p className="muted">{q.plan ? q.plan.title : 'Danh sách thiết bị và căn cứ hợp đồng được chuẩn bị tự động theo quý.'}</p><Link className="button primary" to={planTarget}>{q.plan ? 'Mở kế hoạch quý hiện tại' : `Tạo kế hoạch ${quarterLabels[q.quarter as Quarter]} năm ${q.year}`} →</Link>
 </DashboardSection><DashboardSection title="Tiến độ bảo trì" description="Hạng mục trong các kế hoạch đã duyệt, đang thực hiện và chờ báo cáo." action={{ label: 'Theo dõi', href: '/maintenance-progress?status=IN_PROGRESS' }}>
 {total ? <><div className="dashboard-progress-bar" aria-label={`${total} hạng mục bảo trì`}>{stages.filter(s=>s.count>0).map(s=><span key={s.label} className={s.tone} style={{width:`${s.count/total*100}%`}} title={`${s.label}: ${s.count}`} />)}</div><div className="dashboard-progress-legend">{stages.map(s=><div key={s.label}><i className={s.tone}/><span>{s.label}</span><strong>{s.count}</strong></div>)}</div><div className="dashboard-secondary-counts"><span>Chờ nghiệm thu kỹ thuật <strong>{data.progress.technical}</strong></span><span>Chờ bàn giao <strong>{data.progress.handover}</strong></span></div></> : <EmptyDashboardState>Chưa có kế hoạch đang thực hiện bảo trì.</EmptyDashboardState>}
 </DashboardSection></div>
 <div className="dashboard-two-columns"><DashboardSection title="Tình trạng hợp đồng" description="Sắp hết hạn: trong 30 ngày tới." action={{ label: 'Danh sách hợp đồng', href: '/contracts' }}><div className="dashboard-contract-counts"><Link to="/contracts"><strong>{data.contracts.valid}</strong><span>Còn hiệu lực</span></Link><Link to="/contracts"><strong>{data.contracts.expiring}</strong><span>Sắp hết hạn</span></Link><Link to="/contracts"><strong>{data.contracts.expired}</strong><span>Đã hết hạn</span></Link></div>{data.expiringContracts.length ? <ul className="dashboard-records">{data.expiringContracts.map(c=><li key={c.id}><div><Link className="table-link" to={`/contracts/${c.id}`}>{c.code}</Link><p>{c.provider} · {c.equipmentCount} thiết bị</p></div><StatusBadge label={businessDate(c.endDate)} tone="amber" /></li>)}</ul> : <EmptyDashboardState>Không có hợp đồng sắp hết hạn trong 30 ngày.</EmptyDashboardState>}</DashboardSection>
 <DashboardSection title="Cập nhật gần đây" description="5 cập nhật tiến độ mới nhất."><ItemList items={data.recentProgress} mode="progress" empty="Chưa có cập nhật tiến độ bảo trì." /></DashboardSection></div>
 <DashboardSection title="Báo cáo bảo trì gần đây" action={{ label: 'Xem tất cả', href: '/reports' }}><ReportList reports={data.reports} /></DashboardSection><QuickActions actions={data.quickActions} /></>
}
