package vn.edu.medmaintenance.service;
import static org.assertj.core.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import vn.edu.medmaintenance.security.principal.AuthenticatedUser;
import vn.edu.medmaintenance.persistence.enums.*;
import vn.edu.medmaintenance.api.dto.request.*;
@SpringBootTest @AutoConfigureMockMvc @Transactional
class MaintenanceTrackingIntegrationTest {
 @Autowired JdbcTemplate jdbc;@Autowired MaintenanceTrackingService tracking;@Autowired ExecutionAcceptanceService workflow;
 @Autowired MaintenanceReportService reports;@Autowired ReportDeliveryService delivery;@Autowired QuarterlyPlanningService catalog;
 @Autowired MockMvc mvc;@Autowired vn.edu.medmaintenance.security.jwt.JwtService jwt;
 long plan,a,b,eqA,eqB,departmentA,departmentB,provider,vtyt;String token;
 @BeforeEach void setup(){
  vtyt=jdbc.queryForObject("SELECT id FROM user_account WHERE active AND role_code='PHONG_VTYT' ORDER BY id LIMIT 1",Long.class);
  var departments=jdbc.queryForList("SELECT DISTINCT department_id FROM user_account WHERE active AND role_code='KHOA_PHONG' ORDER BY department_id LIMIT 2",Long.class);departmentA=departments.get(0);departmentB=departments.get(1);
  provider=jdbc.queryForObject("SELECT id FROM service_provider WHERE active ORDER BY id LIMIT 1",Long.class);
  plan=jdbc.queryForObject("INSERT INTO maintenance_plan(title,period_start,period_end,status,created_by_user_id) VALUES ('Bảo trì kiểm thử cập nhật','2026-01-01','2030-12-31','APPROVED',?) RETURNING id",Long.class,vtyt);
  eqA=equipment(departmentA);eqB=equipment(departmentB);a=item(eqA,departmentA);b=item(eqB,departmentB);role(vtyt,UserRole.PHONG_VTYT,null);
 }
 long equipment(long department){return jdbc.queryForObject("INSERT INTO equipment(equipment_code,name,department_id) VALUES (?,'Thiết bị kiểm thử quyền VTYT',?) RETURNING id",Long.class,"TRACK-"+UUID.randomUUID(),department);}
 long item(long equipment,long department){long coverage=jdbc.queryForObject("INSERT INTO maintenance_coverage(equipment_id,provider_id,classification,verified_by_user_id,verified_at,basis_note,effective_from,effective_to,warranty_expires_on) VALUES (?,?,'FREE',?,now(),'Hồ sơ kiểm thử','2026-01-01','2030-12-31','2028-06-30') RETURNING id",Long.class,equipment,provider,vtyt);return jdbc.queryForObject("INSERT INTO maintenance_plan_item(plan_id,equipment_id,department_id_at_plan,status,assigned_provider_id,assignment_route,coverage_id) VALUES (?,?,?,'UNDER_CONTRACT',?,'UNDER_CONTRACT',?) RETURNING id",Long.class,plan,equipment,department,provider,coverage);}
 int version(long item){return jdbc.queryForObject("SELECT version FROM maintenance_plan_item WHERE id=?",Integer.class,item);}
 int planVersion(){return jdbc.queryForObject("SELECT version FROM maintenance_plan WHERE id=?",Integer.class,plan);}
 long start(long item){return workflow.start(item,new StartExecutionRequest(version(item),planVersion())).executionId();}
 void progress(long item,long execution,MaintenanceProgressStatus status,String note){workflow.addProgress(execution,new ProgressRequest(status,note,version(item),null,null));}
 void role(long id,UserRole role,Long department){var principal=new AuthenticatedUser(id,"test",role,department);token=jwt.issue(principal);SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(principal,null,List.of(new org.springframework.security.core.authority.SimpleGrantedAuthority("ROLE_"+role.name()))));}
 void finished(){long x=start(a);progress(a,x,MaintenanceProgressStatus.WORK_DONE,"Đã kiểm tra và hiệu chuẩn.");long y=start(b);progress(b,y,MaintenanceProgressStatus.DAMAGE_DETECTED,"Bơm có rò rỉ, cần xử lý tiếp.");tracking.complete(plan,new FinalizeReportRequest(planVersion()));}
 void finalized(){finished();reports.finalizeReport(plan,new FinalizeReportRequest(planVersion()));}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}
 @Test void providerEquipmentHasDistinctDevicesAndSpecificWarrantyDates(){long contract=jdbc.queryForObject("INSERT INTO maintenance_contract(contract_code,contract_name,provider_id,start_date,end_date) VALUES (?,'Thiết bị theo công ty',?,'2026-01-01','2027-12-31') RETURNING id",Long.class,"TRACK-HD-"+UUID.randomUUID(),provider);jdbc.update("INSERT INTO maintenance_contract_equipment(contract_id,equipment_id) VALUES (?,?),(?,?)",contract,eqA,contract,eqB);var rows=catalog.providerEquipment(provider).stream().filter(r->((Number)r.get("equipment_id")).longValue()==eqA).toList();assertThat(rows).hasSize(1);assertThat(rows.get(0).get("warranty_end_date").toString()).isEqualTo("2028-06-30");assertThat(rows.get(0).get("warranty_start_date").toString()).isEqualTo("2026-01-01");}
 @Test void threeProgressLevelsAndDamageDescriptionAreRecorded(){long execution=start(a);assertThat(tracking.tracking(plan).get(0).get("progress_status")).isIn("IN_PROGRESS","NOT_STARTED");progress(a,execution,MaintenanceProgressStatus.DAMAGE_DETECTED,"Mất tín hiệu cảm biến.");assertThat(tracking.tracking(plan).stream().filter(r->((Number)r.get("item_id")).longValue()==a).findFirst().orElseThrow()).containsEntry("progress_status","DAMAGE_DETECTED").containsEntry("damage_note","Mất tín hiệu cảm biến.");assertThatThrownBy(()->progress(a,execution,MaintenanceProgressStatus.DAMAGE_DETECTED,null)).hasMessageContaining("mô tả hỏng hóc");}
 @Test void completionRequiresAResultForEveryDevice(){long execution=start(a);progress(a,execution,MaintenanceProgressStatus.WORK_DONE,null);assertThatThrownBy(()->tracking.complete(plan,new FinalizeReportRequest(planVersion()))).hasMessageContaining("Cần cập nhật kết quả");assertThat(jdbc.queryForObject("SELECT count(*) FROM maintenance_report WHERE plan_id=?",Long.class,plan)).isZero();assertThat(jdbc.queryForObject("SELECT status FROM maintenance_plan_item WHERE id=?",String.class,a)).isEqualTo("IN_MAINTENANCE");}
 @Test void vtytCompletionCreatesDraftWithoutForgedDepartmentSignatures(){finished();assertThat(jdbc.queryForObject("SELECT status FROM maintenance_plan WHERE id=?",String.class,plan)).isEqualTo("AWAITING_REPORT");var report=reports.get(plan);assertThat(report.status()).isEqualTo(ReportStatus.DRAFT);assertThat(report.completedCount()).isEqualTo(1);assertThat(report.repairRequiredCount()).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT count(*) FROM acceptance_record r JOIN maintenance_execution x ON x.id=r.execution_id JOIN maintenance_plan_item i ON i.id=x.plan_item_id WHERE i.plan_id=?",Long.class,plan)).isZero();assertThat(jdbc.queryForObject("SELECT count(*) FROM status_history h JOIN maintenance_plan_item i ON i.id=h.plan_item_id WHERE i.plan_id=? AND h.action='VTYT_COMPLETE_MAINTENANCE' AND h.actor_user_id=?",Long.class,plan,vtyt)).isEqualTo(2);}
 @Test void draftCannotBeSent(){finished();assertThatThrownBy(()->delivery.send(plan,new FinalizeReportRequest(planVersion()))).hasMessageContaining("Hoàn tất báo cáo");assertThat(jdbc.queryForObject("SELECT count(*) FROM maintenance_report_delivery v JOIN maintenance_report r ON r.id=v.report_id WHERE r.plan_id=?",Long.class,plan)).isZero();}
 @Test void sendingFinalReportCreatesReceiptsAndNotificationsExactlyOnce(){finalized();delivery.send(plan,new FinalizeReportRequest(planVersion()));long before=jdbc.queryForObject("SELECT count(*) FROM user_notification WHERE notification_type='REPORT_SHARED' AND target_url=?",Long.class,"/plans/"+plan+"/report");assertThat(before).isGreaterThanOrEqualTo(3);delivery.send(plan,new FinalizeReportRequest(planVersion()));assertThat(jdbc.queryForObject("SELECT count(*) FROM user_notification WHERE notification_type='REPORT_SHARED' AND target_url=?",Long.class,"/plans/"+plan+"/report")).isEqualTo(before);assertThat(jdbc.queryForObject("SELECT count(*) FROM maintenance_report_delivery v JOIN maintenance_report r ON r.id=v.report_id WHERE r.plan_id=?",Long.class,plan)).isEqualTo(3);}
 @Test void departmentReceivesOnlyItsDevicesAndCannotEditOrSend() throws Exception {finalized();delivery.send(plan,new FinalizeReportRequest(planVersion()));long user=jdbc.queryForObject("SELECT id FROM user_account WHERE active AND role_code='KHOA_PHONG' AND department_id=? ORDER BY id LIMIT 1",Long.class,departmentA);role(user,UserRole.KHOA_PHONG,departmentA);var own=reports.evidence(plan);assertThat(own.items()).hasSize(1);assertThat(own.items().get(0).equipmentCode()).isEqualTo(jdbc.queryForObject("SELECT equipment_code FROM equipment WHERE id=?",String.class,eqA));assertThat(reports.get(plan).workDone()).doesNotContain(jdbc.queryForObject("SELECT equipment_code FROM equipment WHERE id=?",String.class,eqB));assertThat(delivery.received(0,10).content()).anySatisfy(r->{assertThat(r.get("id")).isEqualTo(plan);assertThat(r.get("equipment_count")).isEqualTo(1L);});mvc.perform(post("/api/plans/"+plan+"/report/send").header("Authorization","Bearer "+token).contentType("application/json").content("{\"version\":"+planVersion()+"}")).andExpect(status().isForbidden());}
 @Test void departmentCannotReadBeforeDeliveryAndOnlyVtytMayComplete() throws Exception {finalized();long user=jdbc.queryForObject("SELECT id FROM user_account WHERE active AND role_code='KHOA_PHONG' AND department_id=? ORDER BY id LIMIT 1",Long.class,departmentA);role(user,UserRole.KHOA_PHONG,departmentA);assertThatThrownBy(()->reports.get(plan)).isInstanceOf(BusinessRuleException.class);mvc.perform(post("/api/plans/"+plan+"/complete-maintenance").header("Authorization","Bearer "+token).contentType("application/json").content("{\"version\":"+planVersion()+"}")).andExpect(status().isForbidden());}
}
