CREATE TABLE equipment_maintenance_schedule (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 equipment_id bigint NOT NULL REFERENCES equipment(id),
 quarter text NOT NULL CHECK (quarter IN ('Q1','Q2','Q3','Q4')),
 UNIQUE(equipment_id,quarter)
);
INSERT INTO equipment_maintenance_schedule(equipment_id,quarter)
SELECT id,'Q'||(((id-1)%4)+1) FROM equipment;
CREATE TABLE maintenance_contract_equipment (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 contract_id bigint NOT NULL REFERENCES maintenance_contract(id),
 equipment_id bigint NOT NULL REFERENCES equipment(id),
 UNIQUE(contract_id,equipment_id)
);
CREATE INDEX ix_contract_equipment_device ON maintenance_contract_equipment(equipment_id);
INSERT INTO maintenance_contract_equipment(contract_id,equipment_id)
SELECT DISTINCT contract_id,equipment_id FROM maintenance_coverage WHERE contract_id IS NOT NULL;
ALTER TABLE maintenance_plan ADD COLUMN plan_year integer;
ALTER TABLE maintenance_plan ADD COLUMN plan_quarter text;
ALTER TABLE maintenance_plan ADD CONSTRAINT ck_plan_quarter CHECK (
 (plan_year IS NULL AND plan_quarter IS NULL) OR
 (plan_year IS NOT NULL AND plan_quarter IS NOT NULL AND plan_year BETWEEN 2000 AND 2100 AND plan_quarter IN ('Q1','Q2','Q3','Q4')));
-- Only exact quarter periods are periodic plans; preserve other legacy periods.
WITH candidates AS (
 SELECT id,extract(year FROM period_start)::integer y,'Q'||extract(quarter FROM period_start)::integer q,
 row_number() OVER(PARTITION BY extract(year FROM period_start),extract(quarter FROM period_start) ORDER BY id) n
 FROM maintenance_plan WHERE period_start=date_trunc('quarter',period_start)::date
 AND period_end=(date_trunc('quarter',period_start)+interval '3 months - 1 day')::date
 AND extract(year FROM period_start) BETWEEN 2000 AND 2100
)
UPDATE maintenance_plan p SET plan_year=c.y,plan_quarter=c.q FROM candidates c WHERE p.id=c.id AND c.n=1;
CREATE UNIQUE INDEX uq_active_quarter_plan ON maintenance_plan(plan_year,plan_quarter)
 WHERE plan_year IS NOT NULL AND status NOT IN ('CLOSED','REPORTED');
ALTER TABLE maintenance_plan_item ADD COLUMN contract_id bigint REFERENCES maintenance_contract(id);
UPDATE maintenance_plan_item i SET contract_id=c.contract_id FROM maintenance_coverage c WHERE i.coverage_id=c.id;
