-- A NULL department identifies the board recipient; each recipient receives a report once.
CREATE TABLE maintenance_report_delivery (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 report_id bigint NOT NULL REFERENCES maintenance_report(id),
 department_id bigint REFERENCES department(id),
 sent_by_user_id bigint NOT NULL REFERENCES user_account(id),
 sent_at timestamptz NOT NULL,
 UNIQUE(report_id,department_id)
);
CREATE UNIQUE INDEX uq_report_board_delivery ON maintenance_report_delivery(report_id) WHERE department_id IS NULL;
CREATE INDEX ix_report_department_delivery ON maintenance_report_delivery(department_id,report_id);
-- Previously finalized reports were already available to the board.
INSERT INTO maintenance_report_delivery(report_id,sent_by_user_id,sent_at)
SELECT id,created_by_user_id,finalized_at FROM maintenance_report WHERE status='FINAL';
