import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router'
import { apiRequest } from '../api/client'
import { businessDate } from '../utils/workflowLabels'
import { WorkflowError } from '../components/WorkflowFeedback'
import { StatusBadge } from '../components/StatusBadge'
import { EquipmentWarrantyTable } from '../components/EquipmentWarrantyTable'
import type { CatalogEquipment } from '../types/equipmentCatalog'
interface Contract { id:number;contract_code:string;contract_name:string;provider_id:number;provider_name:string;start_date:string;end_date:string;active:boolean;status:string;equipment_count:number;notes:string }
interface ContractEquipment {id:number;equipment_code:string;name:string;department_name:string;quarters:string}
interface Company {id:number;name:string;contact_details:string;contract_count:number;active_contract_count:number;covered_equipment_count:number}
function ContractTable({rows}:{rows:Contract[]}) {return <div className="table-scroll"><table className="data-table catalog-table"><thead><tr><th>Mã hợp đồng</th><th>Tên hợp đồng</th><th>Ngày bắt đầu</th><th>Ngày hết hạn</th><th>Trạng thái</th><th>Thiết bị</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><Link className="equipment-code-link" to={`/contracts/${c.id}`}>{c.contract_code}</Link></td><td>{c.contract_name}</td><td>{businessDate(c.start_date)}</td><td>{businessDate(c.end_date)}</td><td><StatusBadge label={c.status==='ACTIVE'?'Còn hạn':'Hết hạn'} tone={c.status==='ACTIVE'?'teal':'amber'}/></td><td>{c.equipment_count ?? '—'}</td></tr>)}</tbody></table></div>}
export function ContractListPage() {
 const [rows,setRows]=useState<Company[]>([]);const [search,setSearch]=useState('');const [error,setError]=useState<unknown>(null);const [loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;apiRequest<Company[]>('/api/companies').then(r=>{if(active){setRows(r);setLoading(false)}}).catch(e=>{if(active){setError(e);setLoading(false)}});return()=>{active=false}},[])
 const visible=rows.filter(r=>`${r.name} ${r.contact_details}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')))
 return <div className="page-stack catalog-page"><div className="catalog-hero"><div><p className="eyebrow">ĐỐI TÁC & HỢP ĐỒNG</p><h1>Danh sách hợp đồng</h1><p>Chọn công ty để xem hợp đồng, thiết bị được bảo trì và thời hạn bảo hành.</p></div><span className="catalog-hero-symbol" aria-hidden="true">↗</span></div><WorkflowError error={error}/><div className="catalog-stats"><div><span>Công ty / đơn vị</span><strong>{rows.length}</strong></div><div><span>Tổng hợp đồng</span><strong>{rows.reduce((n,r)=>n+Number(r.contract_count),0)}</strong></div><div><span>Hợp đồng còn hạn</span><strong>{rows.reduce((n,r)=>n+Number(r.active_contract_count),0)}</strong></div></div><section className="panel business-panel catalog-panel"><div className="catalog-toolbar"><label>Tìm công ty<input type="search" placeholder="Tên công ty hoặc thông tin liên hệ…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{loading?<p className="muted">Đang tải công ty…</p>:<div className="table-scroll"><table className="data-table catalog-table"><thead><tr><th>Công ty / Đơn vị</th><th>Liên hệ</th><th>Số hợp đồng</th><th>Hợp đồng còn hạn</th><th>Số thiết bị</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><Link className="company-name" to={`/providers/${p.id}`}><span className="company-avatar" aria-hidden="true">{p.name.charAt(0)}</span><strong>{p.name}</strong><span aria-hidden="true">↗</span></Link></td><td>{p.contact_details || '—'}</td><td>{p.contract_count}</td><td><span className="catalog-count">{p.active_contract_count}</span></td><td>{p.covered_equipment_count}</td></tr>)}</tbody></table></div>}{!loading&&!visible.length&&<p className="empty-state">Không tìm thấy công ty phù hợp.</p>}</section></div>
}
export function ContractDetailPage() {
 const {id}=useParams();const [contract,setContract]=useState<Contract|null>(null);const [rows,setRows]=useState<ContractEquipment[]>([]);const [error,setError]=useState<unknown>(null)
 useEffect(()=>{let active=true;Promise.all([apiRequest<Contract>(`/api/contracts/${id}`),apiRequest<ContractEquipment[]>(`/api/contracts/${id}/equipment`)]).then(([c,r])=>{if(active){setContract(c);setRows(r)}}).catch(e=>{if(active)setError(e)});return()=>{active=false}},[id])
 return <div className="page-stack catalog-page"><Link className="text-link" to={contract?`/providers/${contract.provider_id}`:'/contracts'}>← Danh sách hợp đồng</Link><div className="catalog-hero"><div><p className="eyebrow">CHI TIẾT HỢP ĐỒNG</p><h1>{contract?.contract_name || 'Chi tiết hợp đồng'}</h1><p>{contract?.contract_code}</p></div>{contract&&<StatusBadge label={contract.status==='ACTIVE'?'Còn hạn':'Hết hạn'} tone={contract.status==='ACTIVE'?'teal':'amber'}/>}</div><WorkflowError error={error}/>{contract&&<section className="panel business-panel"><div className="equipment-detail-grid"><div><span>Công ty</span><Link className="table-link" to={`/providers/${contract.provider_id}`}>{contract.provider_name}</Link></div><div><span>Ngày bắt đầu</span><strong>{businessDate(contract.start_date)}</strong></div><div><span>Ngày hết hạn</span><strong>{businessDate(contract.end_date)}</strong></div></div><p>{contract.notes}</p></section>}<section className="panel business-panel"><div className="panel-heading"><h2>Thiết bị thuộc hợp đồng</h2><span className="muted">{rows.length} thiết bị</span></div><div className="table-scroll"><table className="data-table catalog-table"><thead><tr><th>Mã thiết bị</th><th>Tên thiết bị</th><th>Khoa/Phòng</th><th>Lịch bảo trì</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link className="equipment-code-link" to={`/equipment/${r.id}`}>{r.equipment_code}</Link></td><td>{r.name}</td><td>{r.department_name}</td><td>{r.quarters}</td></tr>)}</tbody></table></div></section></div>
}
interface ProviderDetail {id:number;code:string;name:string;contact_details:string;active:boolean;covered_equipment_count:number;contracts:Contract[]}
export function ProviderDetailPage() {
 const {id}=useParams();const [provider,setProvider]=useState<ProviderDetail|null>(null);const [equipment,setEquipment]=useState<CatalogEquipment[]>([]);const [search,setSearch]=useState('');const [error,setError]=useState<unknown>(null)
 useEffect(()=>{let active=true;Promise.all([apiRequest<ProviderDetail>(`/api/providers/${id}/detail`),apiRequest<(Omit<CatalogEquipment,'contracts'> & {contracts:string})[]>(`/api/providers/${id}/equipment`)]).then(([p,rows])=>{if(active){setProvider(p);setEquipment(rows.map(r=>({...r,contracts:undefined,contracts_label:r.contracts})))}}).catch(e=>{if(active)setError(e)});return()=>{active=false}},[id])
 const visible=equipment.filter(r=>`${r.equipment_code} ${r.equipment_name} ${r.department_name}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')))
 return <div className="page-stack catalog-page"><Link className="text-link" to="/contracts">← Danh sách hợp đồng</Link><div className="catalog-hero"><div><p className="eyebrow">HỒ SƠ CÔNG TY / ĐƠN VỊ</p><h1>{provider?.name || 'Công ty / Đơn vị'}</h1><p>{provider?.contact_details || 'Thông tin liên hệ đang được cập nhật'}</p></div><span className="catalog-hero-symbol" aria-hidden="true">{provider?.code?.slice(0,2) || 'CT'}</span></div><WorkflowError error={error}/>{provider&&<><div className="catalog-stats"><div><span>Hợp đồng</span><strong>{provider.contracts.length}</strong></div><div><span>Thiết bị thuộc công ty</span><strong>{equipment.length}</strong></div><div><span>Bảo hành còn hạn</span><strong>{equipment.filter(r=>r.warranty_status==='VALID').length}</strong></div></div><section className="panel business-panel catalog-panel"><div className="panel-heading"><h2>Danh sách hợp đồng</h2><span className="muted">Thời hạn hợp đồng bảo trì</span></div><ContractTable rows={provider.contracts}/></section><section className="panel business-panel catalog-panel"><div className="panel-heading"><div><h2>Danh sách thiết bị</h2><p>Thiết bị được công ty bảo trì, kèm thời hạn bảo hành trong hồ sơ.</p></div><span className="catalog-count">{equipment.length} thiết bị</span></div><div className="catalog-toolbar"><label>Tìm thiết bị<input type="search" placeholder="Mã, tên thiết bị hoặc khoa/phòng…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{visible.length?<EquipmentWarrantyTable rows={visible} withContracts/>:<p className="empty-state">Không có thiết bị phù hợp.</p>}</section></>}</div>
}
