import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes, useLocation } from 'react-router'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { DashboardPage } from './DashboardPage'
import { dashboardApi } from '../api/dashboardApi'
import type { DashboardData } from '../types/dashboard'
import type { Role } from '../types/auth'
const auth=vi.hoisted(()=>({user:{id:1,username:'test',role:'PHONG_VTYT' as Role}}))
vi.mock('../auth/useAuth',()=>({useAuth:()=>auth}))
vi.mock('../api/dashboardApi',()=>({dashboardApi:{get:vi.fn()}}))
const base={generatedAt:'2026-10-05T00:00:00Z',quickActions:[]}
const vtyt:DashboardData={...base,role:'PHONG_VTYT',summary:{scheduled:8,activeContracts:3,maintaining:2,technical:1,awaitingReport:1},attention:[{title:'Kế hoạch cần chỉnh sửa',detail:'Đã có ý kiến BGĐ',status:'REVISION_REQUIRED',at:null,href:'/plans/7/edit',cta:'Xem ý kiến BGĐ'}],currentQuarter:{year:2026,quarter:'Q4',scheduled:8,underContract:6,outsideContract:2,inProgress:0,completed:0,plan:null},progress:{notStarted:6,inProgress:2,workDone:0,damaged:0,technical:1,handover:0},contracts:{valid:3,expiring:0,expired:1},expiringContracts:[],recentProgress:[],reports:[],quickActions:[{label:'Danh sách thiết bị',href:'/equipment'}]}
const bgd:DashboardData={...base,role:'BAN_GIAM_DOC',summary:{pendingPlans:3,pendingProviders:2,approvedThisMonth:4,revisedThisMonth:1,reportsThisMonth:0},pending:[],decisions:[],reports:[]}
const khoa:DashboardData={...base,role:'KHOA_PHONG',departmentId:1,departmentName:'Khoa Nội tổng hợp',summary:{equipment:4,maintaining:1,handover:1,completedRecently:2},handover:[{itemId:11,planId:5,equipmentId:2,equipmentCode:'TB-OWN',equipmentName:'Máy theo dõi',provider:'An Phát',status:'AWAITING_HANDOVER',at:'2026-10-05T00:00:00Z',note:null,actor:null}],active:[],history:[],quickActions:[{label:'Lịch sử bảo trì',href:'/equipment'}]}
const admin:DashboardData={...base,role:'ADMIN',summary:{activeAccounts:5,inactiveAccounts:1,departments:10,providers:3,contracts:9},accountsByRole:[{role:'ADMIN',count:1},{role:'KHOA_PHONG',count:2}],quality:[{label:'Thiết bị chưa có lịch quý',count:2,href:'/admin/equipment'}],quickActions:[{label:'Quản lý tài khoản',href:'/admin/accounts'}]}
function Destination(){const location=useLocation();return <p>Đích: {location.pathname}{location.search}</p>}
function page(){return render(<MemoryRouter initialEntries={['/dashboard']}><Routes><Route path="/dashboard" element={<DashboardPage/>}/><Route path="*" element={<Destination/>}/></Routes></MemoryRouter>)}
afterEach(cleanup)
beforeEach(()=>{vi.resetAllMocks();auth.user.role='PHONG_VTYT';vi.mocked(dashboardApi.get).mockResolvedValue(vtyt)})
it.each<[DashboardData,string]>([[vtyt,'Tổng quan Phòng Vật tư Y tế'],[bgd,'Tổng quan Ban Giám đốc'],[khoa,'Khoa/Phòng: Khoa Nội tổng hợp'],[admin,'Tổng quan quản trị hệ thống']])('renders the authenticated %s dashboard using one aggregate request',async(data,title)=>{auth.user.role=data.role;vi.mocked(dashboardApi.get).mockResolvedValue(data);page();await screen.findByRole('heading',{name:title});expect(dashboardApi.get).toHaveBeenCalledTimes(1);if(data.role==='BAN_GIAM_DOC'){expect(screen.queryByText('Danh sách thiết bị')).toBeNull();expect(screen.queryByText('Tình trạng hợp đồng')).toBeNull()}})
it('attention CTA opens the existing edit/revision screen',async()=>{page();fireEvent.click(await screen.findByRole('link',{name:'Xem ý kiến BGĐ →'}));expect(await screen.findByText('Đích: /plans/7/edit')).toBeTruthy()})
it('current-quarter creation passes year and quarter without creating a plan',async()=>{page();fireEvent.click(await screen.findByRole('link',{name:'Tạo kế hoạch Quý IV năm 2026 →'}));expect(await screen.findByText('Đích: /plans/new?year=2026&quarter=Q4')).toBeTruthy()})
it('quick action navigates to the equipment module',async()=>{page();fireEvent.click(await screen.findByRole('link',{name:'Danh sách thiết bị'}));expect(await screen.findByText('Đích: /equipment')).toBeTruthy()})
it('BGD approval card opens a filtered queue and displays intentional empty states',async()=>{auth.user.role='BAN_GIAM_DOC';vi.mocked(dashboardApi.get).mockResolvedValue(bgd);page();await screen.findByText('Không có hồ sơ nào đang chờ phê duyệt.');fireEvent.click(screen.getByRole('link',{name:/Kế hoạch chờ phê duyệt/}));expect(await screen.findByText('Đích: /approvals?requestType=PLAN_APPROVAL')).toBeTruthy()})
it('department handover CTA opens its exact item',async()=>{auth.user.role='KHOA_PHONG';vi.mocked(dashboardApi.get).mockResolvedValue(khoa);page();fireEvent.click(await screen.findByRole('link',{name:'Xác nhận bàn giao →'}));expect(await screen.findByText('Đích: /plans/5/items/11/execution')).toBeTruthy()})
it('ADMIN account metric navigates with the active filter',async()=>{auth.user.role='ADMIN';vi.mocked(dashboardApi.get).mockResolvedValue(admin);page();fireEvent.click(await screen.findByRole('link',{name:/Tài khoản hoạt động/}));expect(await screen.findByText('Đích: /admin/accounts?active=true')).toBeTruthy()})
it('retries a failed aggregate request and hides mismatched role data',async()=>{vi.mocked(dashboardApi.get).mockRejectedValueOnce(new Error('Temporary failure')).mockResolvedValueOnce(bgd).mockResolvedValueOnce(vtyt);page();fireEvent.click(await screen.findByRole('button',{name:'Thử lại'}));await waitFor(()=>expect(dashboardApi.get).toHaveBeenCalledTimes(2));expect(await screen.findByRole('alert')).toBeTruthy();expect(screen.queryByRole('heading',{name:'Tổng quan Ban Giám đốc'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Thử lại'}));expect(await screen.findByRole('heading',{name:'Tổng quan Phòng Vật tư Y tế'})).toBeTruthy()})
