import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate } from 'react-router'
import { apiRequest } from '../api/client'
import { departmentsApi } from '../api/departmentsApi'
import { providersApi } from '../api/providersApi'
import { WorkflowError } from '../components/WorkflowFeedback'
import { UserInputError } from '../utils/UserInputError'
import type { Department, Provider } from '../types/workflow'
interface Contract { id:number; contract_code:string; contract_name:string; provider_name:string; active:boolean; status:string }
export function EquipmentFormPage() {
 const navigate=useNavigate();const [departments,setDepartments]=useState<Department[]>([]);const [providers,setProviders]=useState<Provider[]>([]);const [contracts,setContracts]=useState<Contract[]>([])
 const [mode,setMode]=useState('NONE');const [companyMode,setCompanyMode]=useState('EXISTING');const [quarters,setQuarters]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState<unknown>(null)
 useEffect(()=>{let active=true;Promise.all([departmentsApi.list(),providersApi.list(),apiRequest<Contract[]>('/api/contracts')]).then(([d,p,c])=>{if(active){setDepartments(d);setProviders(p);setContracts(c);setLoading(false)}}).catch(e=>{if(active){setError(e);setLoading(false)}});return()=>{active=false}},[])
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setError(null);if(!quarters.length){setError(new UserInputError('Chọn ít nhất một quý bảo trì.'));return}const form=new FormData(event.currentTarget);const value=(key:string)=>String(form.get(key)??'').trim();setBusy(true)
  try{await apiRequest('/api/equipment',{method:'POST',body:{equipmentCode:value('code'),name:value('name'),departmentId:Number(value('department')),model:value('model')||null,serialNumber:value('serial')||null,quarters,warrantyEndDate:value('warranty')||null,contractId:mode==='EXISTING'?Number(value('contract')):null,newContract:mode==='NEW'?{code:value('contractCode'),name:value('contractName'),startDate:value('start'),endDate:value('end'),providerId:companyMode==='EXISTING'?Number(value('provider')):null,newCompany:companyMode==='NEW'?{code:value('companyCode'),name:value('companyName'),contact:value('contact')||null}:null}:null}});navigate('/equipment')}catch(e){setError(e)}finally{setBusy(false)}
 }
 return <div className="page-stack catalog-page"><Link className="text-link" to="/equipment">← Danh sách thiết bị</Link><div className="catalog-hero"><div><p className="eyebrow">QUẢN LÝ THIẾT BỊ</p><h1>Thêm thiết bị</h1><p>Nhập hồ sơ, lịch bảo trì và hợp đồng áp dụng cho thiết bị mới.</p></div></div><WorkflowError error={error}/>{loading?<p>Đang tải danh mục…</p>:<form className="plan-form equipment-create-form" onSubmit={event=>void submit(event)}><fieldset disabled={busy}>
 <section className="panel business-panel"><h2>Thông tin thiết bị</h2><div className="form-grid"><label>Mã thiết bị<input name="code" required maxLength={100}/></label><label>Tên thiết bị<input name="name" required maxLength={300}/></label><label>Khoa/Phòng<select name="department" required defaultValue=""><option value="" disabled>Chọn khoa/phòng</option>{departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Mẫu thiết bị<input name="model" maxLength={200}/></label><label>Số serial<input name="serial" maxLength={200}/></label><label>Ngày hết bảo hành<input name="warranty" type="date"/></label></div><fieldset className="quarter-choice"><legend>Quý bảo trì định kỳ</legend><div className="decision-options">{['Q1','Q2','Q3','Q4'].map((q,i)=><label key={q}><input type="checkbox" checked={quarters.includes(q)} onChange={e=>setQuarters(v=>e.target.checked?[...v,q]:v.filter(x=>x!==q))}/>Quý {i+1}</label>)}</div></fieldset></section>
 <section className="panel business-panel"><h2>Hợp đồng bảo trì</h2><div className="form-grid"><label>Hợp đồng áp dụng<select value={mode} onChange={e=>setMode(e.target.value)}><option value="NONE">Chưa có hợp đồng</option><option value="EXISTING">Chọn hợp đồng hiện có</option><option value="NEW">Tạo hợp đồng mới</option></select></label>{mode==='EXISTING'&&<label>Hợp đồng<select name="contract" required defaultValue=""><option value="" disabled>Chọn hợp đồng</option>{contracts.filter(c=>c.active&&c.status!=='INACTIVE').map(c=><option key={c.id} value={c.id}>{c.contract_code} · {c.provider_name} · {c.contract_name}</option>)}</select></label>}
 {mode==='NEW'&&<><label>Mã hợp đồng<input name="contractCode" required maxLength={100}/></label><label>Tên hợp đồng<input name="contractName" required maxLength={300}/></label><label>Ngày bắt đầu<input name="start" type="date" required/></label><label>Ngày hết hạn<input name="end" type="date" required/></label><label>Công ty bảo trì<select value={companyMode} onChange={e=>setCompanyMode(e.target.value)}><option value="EXISTING">Công ty hiện có</option><option value="NEW">Thêm công ty mới</option></select></label>{companyMode==='EXISTING'?<label>Chọn công ty<select name="provider" required defaultValue=""><option value="" disabled>Chọn công ty</option>{providers.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:<><label>Mã công ty<input name="companyCode" required maxLength={100}/></label><label>Tên công ty<input name="companyName" required maxLength={300}/></label><label className="wide-field">Thông tin liên hệ<input name="contact" maxLength={1000}/></label></>}</>}
 </div>{mode==='NEW'&&<p className="retention-note">Hợp đồng và công ty mới sẽ xuất hiện trong danh sách hợp đồng khi lưu thiết bị.</p>}</section><div className="form-actions"><Link className="button secondary" to="/equipment">Hủy</Link><button className="button primary" type="submit">{busy?'Đang lưu…':'Lưu thiết bị'}</button></div></fieldset></form>}</div>
}
