import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router'
import { plansApi } from '../api/plansApi'
import { executionsApi } from '../api/executionsApi'
import { maintenanceTrackingApi } from '../api/maintenanceTrackingApi'
import type { TrackingItem } from '../api/maintenanceTrackingApi'
import { Pagination } from '../components/Pagination'
import { StatusBadge } from '../components/StatusBadge'
import { Modal } from '../components/Modal'
import { UserInputError } from '../utils/UserInputError'
import { WorkflowError, WorkflowSuccess } from '../components/WorkflowFeedback'
import { progressLabels } from '../utils/executionProgress'
import type { MaintenanceProgressStatus } from '../types/execution'
import type { PageResponse, Plan, PlanStatus } from '../types/workflow'
import { businessDate, planStatusLabels } from '../utils/workflowLabels'
const trackingStates:PlanStatus[]=['APPROVED','IN_PROGRESS','AWAITING_REPORT']
export function MaintenanceProgressPage(){
 const {planId}=useParams();const id=Number(planId);const inPlan=planId!==undefined;const navigate=useNavigate();const [search,setSearch]=useSearchParams()
 const requestedStatus=search.get('status') as PlanStatus|null;const status=requestedStatus&&trackingStates.includes(requestedStatus)?requestedStatus:undefined
 const [page,setPage]=useState(0);const [plans,setPlans]=useState<PageResponse<Plan>|null>(null);const [plan,setPlan]=useState<Plan|null>(null);const [items,setItems]=useState<TrackingItem[]>([])
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<number|string|null>(null);const [error,setError]=useState<unknown>(null);const [notice,setNotice]=useState<string|null>(null);const [refresh,setRefresh]=useState(0)
 const [damage,setDamage]=useState<TrackingItem|null>(null);const [note,setNote]=useState('');const inFlight=useRef(false)
 useEffect(()=>{let active=true;async function load(){setLoading(true);setError(null);try{if(inPlan){if(!Number.isInteger(id)||id<=0)throw new UserInputError('Đường dẫn kế hoạch không hợp lệ.');const p=await plansApi.detail(id);const rows=trackingStates.includes(p.status)?await maintenanceTrackingApi.list(id):[];if(active){setPlan(p);setItems(rows)}}else{const rows=await maintenanceTrackingApi.plans(page,status);if(active)setPlans(rows)}}catch(e){if(active)setError(e)}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[id,inPlan,page,status,refresh])
 useEffect(()=>{const reload=()=>{if(!inFlight.current)setRefresh(r=>r+1)};window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload)},[])
 const completed=items.filter(r=>r.progress_status==='WORK_DONE').length;const damaged=items.filter(r=>r.progress_status==='DAMAGE_DETECTED').length;const ready=items.length>0&&completed+damaged===items.length
 const notStarted=items.some(r=>['UNDER_CONTRACT','ASSIGNED_EXTERNAL','REWORK_REQUIRED'].includes(r.status));const ongoing=items.some(r=>r.status==='IN_MAINTENANCE'&&r.progress_status==='IN_PROGRESS')
 async function act(key:number|string,action:()=>Promise<unknown>,message:string){if(inFlight.current)return;inFlight.current=true;setBusy(key);setError(null);try{await action();setNotice(message);setDamage(null);setRefresh(r=>r+1)}catch(e){setError(e)}finally{inFlight.current=false;setBusy(null)}}
 function update(row:TrackingItem,value:MaintenanceProgressStatus,description:string|null=null){if(!row.execution_id)return;if(value==='DAMAGE_DETECTED'&&!description?.trim()){setError(new UserInputError('Vui lòng mô tả hỏng hóc.'));return}void act(row.item_id,()=>executionsApi.updateProgress(row.execution_id!,value,description,row.version),'Đã cập nhật kết quả bảo trì.')}
 function complete(){if(!plan||!ready||!window.confirm('Hoàn thành bảo trì và tạo báo cáo từ các kết quả đã ghi nhận?'))return;void act('complete',async()=>{await maintenanceTrackingApi.complete(plan.id,plan.version);navigate(`/plans/${plan.id}/report`)},'Đã hoàn thành bảo trì và tạo báo cáo.')}
 return <div className="page-stack maintenance-progress-page catalog-page"><div className="catalog-hero"><div><p className="eyebrow">ĐIỀU PHỐI BẢO TRÌ</p><h1>Theo dõi tiến độ bảo trì</h1><p>{inPlan?'Bắt đầu kế hoạch → ghi kết quả thiết bị → hoàn thành và lập báo cáo.':'Chọn kế hoạch để bắt đầu bảo trì hoặc cập nhật kết quả.'}</p></div><button className="button secondary" disabled={busy!==null} onClick={()=>setRefresh(r=>r+1)}>Tải lại</button></div>{inPlan&&<Link className="text-link" to="/maintenance-progress">← Danh sách tiến độ bảo trì</Link>}<WorkflowSuccess message={notice}/>{!damage&&<WorkflowError error={error}/>}
 {loading?<p className="muted">Đang tải tiến độ bảo trì…</p>:!inPlan&&plans?<section className="panel business-panel"><div className="panel-heading"><div><h2>Kế hoạch bảo trì</h2><p>{plans.totalElements} kế hoạch</p></div><label className="inline-filter">Trạng thái kế hoạch<select value={status??''} onChange={e=>{setSearch(e.target.value?{status:e.target.value}:{});setPage(0)}}><option value="">Tất cả</option>{trackingStates.map(s=><option key={s} value={s}>{planStatusLabels[s]}</option>)}</select></label></div>{plans.content.length?<div className="progress-plan-grid">{plans.content.map(p=><article className="progress-plan-card" key={p.id}><StatusBadge label={planStatusLabels[p.status]} tone={p.status==='AWAITING_REPORT'?'teal':'neutral'}/><h3>{p.title}</h3><p>{businessDate(p.periodStart)} – {businessDate(p.periodEnd)}</p><p>{p.equipmentCount??'—'} thiết bị</p><Link className="button secondary" to={`/maintenance-progress/plans/${p.id}`}>{p.status==='AWAITING_REPORT'?'Xem kết quả':'Cập nhật tiến độ'}</Link></article>)}</div>:<p className="empty-state">Chưa có kế hoạch cần theo dõi.</p>}<Pagination data={plans} onPage={setPage}/></section>:plan&&!trackingStates.includes(plan.status)?<section className="panel business-panel"><h2>{plan.title}</h2><p className="retention-note">Kế hoạch chưa được phê duyệt hoặc đã kết thúc bảo trì.</p><Link className="button secondary" to="/maintenance-history">Xem lịch sử bảo trì</Link></section>:plan?<>
 <div className="catalog-stats progress-stats"><div><span>Tổng thiết bị</span><strong>{items.length}</strong></div><div><span>Đang bảo trì</span><strong>{items.filter(r=>r.progress_status==='IN_PROGRESS').length}</strong></div><div><span>Bảo trì xong</span><strong>{completed}</strong></div><div><span>Có hỏng hóc</span><strong>{damaged}</strong></div></div>
 <section className="panel business-panel"><div className="panel-heading"><div><h2>{plan.title}</h2><p>Đã ghi kết quả {completed+damaged}/{items.length} thiết bị.</p></div><StatusBadge label={planStatusLabels[plan.status]} tone={plan.status==='AWAITING_REPORT'?'teal':'neutral'}/></div>
 <ol className="maintenance-steps"><li className={plan.status!=='APPROVED'?'step-done':''}><span>1</span>Bắt đầu kế hoạch</li><li className={ready?'step-done':''}><span>2</span>Ghi kết quả thiết bị</li><li className={plan.status==='AWAITING_REPORT'?'step-done':''}><span>3</span>Hoàn thành & lập báo cáo</li></ol>
 {plan.pendingVendorApproval&&<p className="retention-note">Thông tin phân công bảo trì chưa đầy đủ. Hãy tải lại để cập nhật kế hoạch.</p>}
 <div className="progress-bulk-actions">{notStarted&&<button className="button primary" disabled={busy!==null||!!plan.pendingVendorApproval} onClick={()=>void act('start',()=>maintenanceTrackingApi.startAll(plan.id,plan.version),'Đã bắt đầu bảo trì toàn bộ kế hoạch.')}>{busy==='start'?'Đang bắt đầu…':'Bắt đầu kế hoạch'}</button>}{ongoing&&<button className="button secondary" disabled={busy!==null} onClick={()=>void act('done',()=>maintenanceTrackingApi.markWorkDone(plan.id,plan.version),'Đã đánh dấu các thiết bị đang bảo trì là xong; kết quả hỏng hóc được giữ lại.')}>Đánh dấu tất cả đã xong</button>}</div>
 <div className="table-scroll"><table className="data-table catalog-table tracking-table"><thead><tr><th>Thiết bị / khoa</th><th>Công ty bảo trì</th><th>Kết quả bảo trì</th><th>Ghi chú</th></tr></thead><tbody>{items.map(row=>{const canWork=row.status==='IN_MAINTENANCE'&&row.execution_id&&plan.status==='IN_PROGRESS';return <tr key={row.item_id} className={row.progress_status==='DAMAGE_DETECTED'?'tracking-damage-row':row.progress_status==='WORK_DONE'?'tracking-done-row':''}><td><strong>{row.equipment_code} · {row.equipment_name}</strong><span className="row-sub">{row.department_name}</span></td><td>{row.provider_name||'Chưa phân công'}</td><td>{canWork?<select aria-label={`Tiến độ ${row.equipment_code}`} value={row.progress_status} disabled={busy!==null} onChange={e=>{const value=e.target.value as MaintenanceProgressStatus;if(value==='DAMAGE_DETECTED'){setDamage(row);setNote(row.damage_note||'');setError(null)}else update(row,value)}}>{Object.entries(progressLabels).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select>:<StatusBadge label={row.progress_status==='NOT_STARTED'?'Chưa bắt đầu':progressLabels[row.progress_status]} tone={row.progress_status==='WORK_DONE'?'teal':row.progress_status==='DAMAGE_DETECTED'?'amber':'neutral'}/>}</td><td>{row.damage_note||row.work_note||'—'}{canWork&&row.progress_status==='DAMAGE_DETECTED'&&<button className="text-link plain-button" onClick={()=>{setDamage(row);setNote(row.damage_note||'');setError(null)}}>Sửa mô tả hỏng hóc</button>}</td></tr>})}</tbody></table></div>
 <div className="maintenance-completion-panel"><div><h3>{plan.status==='AWAITING_REPORT'?'Bảo trì đã hoàn thành':'Hoàn thành bảo trì'}</h3><p>{plan.status==='AWAITING_REPORT'?'Kết quả đã được lưu vào lịch sử. Mở báo cáo để kiểm tra và gửi.':ready?'Tất cả thiết bị đã có kết quả, có thể lập báo cáo.':'Ghi kết quả “Bảo trì xong” hoặc “Có hỏng hóc” cho tất cả thiết bị.'}</p></div>{plan.status==='AWAITING_REPORT'?<Link className="button primary" to={`/plans/${plan.id}/report`}>Mở báo cáo bảo trì</Link>:<button className="button primary" disabled={!ready||busy!==null} onClick={complete}>Hoàn thành bảo trì & tạo báo cáo</button>}</div>
 </section></>:null}
 {damage&&<Modal title={`Hỏng hóc · ${damage.equipment_code}`} onClose={()=>{if(busy===null){setDamage(null);setError(null)}}}><WorkflowError error={error}/><form onSubmit={e=>{e.preventDefault();update(damage,'DAMAGE_DETECTED',note.trim())}}><label className="block-label">Mô tả hỏng hóc<textarea required rows={4} autoFocus value={note} disabled={busy!==null} onChange={e=>setNote(e.target.value)}/></label><div className="form-actions"><button type="button" className="button secondary" disabled={busy!==null} onClick={()=>{setDamage(null);setError(null)}}>Hủy</button><button className="button primary" disabled={busy!==null}>Lưu hỏng hóc</button></div></form></Modal>}
 </div>
}
