import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router'
import { plansApi } from '../api/plansApi'
import { executionsApi } from '../api/executionsApi'
import { maintenanceTrackingApi } from '../api/maintenanceTrackingApi'
import type { TrackingItem } from '../api/maintenanceTrackingApi'
import { Pagination } from '../components/Pagination'
import { StatusBadge } from '../components/StatusBadge'
import { UserInputError } from '../utils/UserInputError'
import { WorkflowError, WorkflowSuccess } from '../components/WorkflowFeedback'
import { progressLabels } from '../utils/executionProgress'
import type { MaintenanceProgressStatus } from '../types/execution'
import type { PageResponse, Plan, PlanStatus, PlanItemStatus } from '../types/workflow'
import { businessDate, dateTime, planStatusLabels } from '../utils/workflowLabels'
const trackingStates:PlanStatus[]=['APPROVED','IN_PROGRESS','AWAITING_REPORT']
export function MaintenanceProgressPage(){
 const {planId}=useParams();const id=Number(planId);const inPlan=planId!==undefined;const navigate=useNavigate();const [search,setSearch]=useSearchParams()
 const itemFilter=search.get('itemStatus')==='AWAITING_TECHNICAL_ACCEPTANCE'?'AWAITING_TECHNICAL_ACCEPTANCE' as PlanItemStatus:undefined
 const requestedStatus=search.get('status') as PlanStatus|null;const status=requestedStatus&&trackingStates.includes(requestedStatus)?requestedStatus:'APPROVED'
 const [page,setPage]=useState(0);const [plans,setPlans]=useState<PageResponse<Plan>|null>(null);const [plan,setPlan]=useState<Plan|null>(null);const [items,setItems]=useState<TrackingItem[]>([])
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<number|string|null>(null);const [error,setError]=useState<unknown>(null);const [notice,setNotice]=useState<string|null>(null);const [refresh,setRefresh]=useState(0)
 const [changes,setChanges]=useState<Record<number,{status:MaintenanceProgressStatus;note:string}>>({});const inFlight=useRef(false)
 useEffect(()=>{setPage(0)},[planId])
 useEffect(()=>{let active=true;async function load(){setLoading(true);setError(null);try{if(inPlan){if(!Number.isInteger(id)||id<=0)throw new UserInputError('Đường dẫn kế hoạch không hợp lệ.');const p=await plansApi.detail(id);const rows=trackingStates.includes(p.status)?await maintenanceTrackingApi.list(id):[];if(active){setPlan(p);setItems(rows);setChanges({})}}else{const rows=itemFilter?await plansApi.list(page,10,status,itemFilter):await plansApi.list(page,10,status);if(active)setPlans(rows)}}catch(e){if(active)setError(e)}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[id,inPlan,page,status,itemFilter,refresh])
 const completed=items.filter(r=>r.progress_status==='WORK_DONE').length;const damaged=items.filter(r=>r.progress_status==='DAMAGE_DETECTED').length;const ready=items.length>0&&completed+damaged===items.length
 function change(row:TrackingItem,patch:Partial<{status:MaintenanceProgressStatus;note:string}>){setChanges(c=>({...c,[row.item_id]:{...(c[row.item_id]??{status:row.progress_status==='NOT_STARTED'?'IN_PROGRESS':row.progress_status,note:''}),...patch}}))}
 async function act(key:number|string,action:()=>Promise<unknown>,message:string){if(inFlight.current)return;inFlight.current=true;setBusy(key);setError(null);try{await action();setNotice(message);setRefresh(r=>r+1)}catch(e){setError(e)}finally{inFlight.current=false;setBusy(null)}}
 function start(row:TrackingItem){if(!plan)return;void act(row.item_id,()=>executionsApi.start(row.item_id,row.version,plan.version),'Đã bắt đầu bảo trì thiết bị.')}
 function update(row:TrackingItem){if(!row.execution_id)return;const value=changes[row.item_id]??{status:row.progress_status==='NOT_STARTED'?'IN_PROGRESS':row.progress_status,note:''};if(value.status==='DAMAGE_DETECTED'&&!value.note.trim()){setError(new UserInputError(`Vui lòng mô tả hỏng hóc của ${row.equipment_code}.`));return}void act(row.item_id,()=>executionsApi.updateProgress(row.execution_id!,value.status,value.note.trim()||null,row.version),'Đã lưu tiến độ bảo trì.')}
 function complete(){if(!plan||!ready||!window.confirm('Xác nhận kết quả toàn bộ thiết bị và hoàn thành bảo trì? Hệ thống sẽ tạo bản nháp báo cáo để bạn kiểm tra.'))return;void act('complete',async()=>{await maintenanceTrackingApi.complete(plan.id,plan.version);navigate(`/plans/${plan.id}/report`)},'Đã hoàn thành bảo trì và tạo báo cáo.')}
 return <div className="page-stack maintenance-progress-page catalog-page"><div className="catalog-hero"><div><p className="eyebrow">ĐIỀU PHỐI BẢO TRÌ</p><h1>Theo dõi tiến độ bảo trì</h1><p>{inPlan?'Cập nhật kết quả từng thiết bị, sau đó xác nhận hoàn thành để lập báo cáo.':'Chọn kế hoạch đã được BGĐ phê duyệt để theo dõi và cập nhật bảo trì.'}</p></div><button className="button secondary" onClick={()=>setRefresh(r=>r+1)}>Tải lại</button></div>{inPlan&&<Link className="text-link" to={`/maintenance-progress?status=${plan?.status==='AWAITING_REPORT'?'AWAITING_REPORT':plan?.status==='IN_PROGRESS'?'IN_PROGRESS':'APPROVED'}`}>← Các kế hoạch đã phê duyệt</Link>}<WorkflowSuccess message={notice}/><WorkflowError error={error}/>
 {loading?<p className="muted">Đang tải tiến độ bảo trì…</p>:!inPlan&&plans?<section className="panel business-panel"><div className="panel-heading"><div><h2>Kế hoạch bảo trì</h2><p>{plans.totalElements} kế hoạch trong trạng thái được chọn</p></div><label className="inline-filter">Trạng thái kế hoạch<select value={status} onChange={e=>{setSearch({status:e.target.value});setPage(0)}}>{trackingStates.map(s=><option key={s} value={s}>{planStatusLabels[s]}</option>)}</select></label></div>{plans.content.length?<div className="progress-plan-grid">{plans.content.filter(p=>p.status===status).map(p=><article className="progress-plan-card" key={p.id}><StatusBadge label={planStatusLabels[p.status]} tone={p.status==='AWAITING_REPORT'?'teal':'neutral'}/><h3>{p.title}</h3><p>{businessDate(p.periodStart)} – {businessDate(p.periodEnd)}</p><p>{p.equipmentCount ?? '—'} thiết bị · Người lập: {p.createdByName}</p><Link className="button secondary" to={`/maintenance-progress/plans/${p.id}`}>Theo dõi kế hoạch</Link></article>)}</div>:<p className="empty-state">Không có kế hoạch trong trạng thái này.</p>}<Pagination data={plans} onPage={setPage}/></section>:plan&&!trackingStates.includes(plan.status)?<section className="panel business-panel"><h2>{plan.title}</h2><p className="retention-note">Kế hoạch này chưa được phê duyệt hoặc đã kết thúc theo dõi tiến độ.</p><Link to={`/plans/${plan.id}`}>Xem thông tin kế hoạch</Link></section>:plan?<>
 <div className="catalog-stats progress-stats"><div><span>Tổng thiết bị</span><strong>{items.length}</strong></div><div><span>Đang bảo trì</span><strong>{items.filter(r=>r.progress_status==='IN_PROGRESS').length}</strong></div><div><span>Bảo trì xong</span><strong>{completed}</strong></div><div><span>Có hỏng hóc</span><strong>{damaged}</strong></div></div>
 <section className="panel business-panel"><div className="panel-heading"><div><h2>{plan.title}</h2><p>Đã ghi nhận kết quả {completed+damaged}/{items.length} thiết bị.</p></div><StatusBadge label={planStatusLabels[plan.status]} tone={plan.status==='AWAITING_REPORT'?'teal':'neutral'}/></div><div className="maintenance-result-bar" aria-label={`Đã ghi nhận kết quả ${completed+damaged} trên ${items.length} thiết bị`}><span style={{width:`${items.length?completed/items.length*100:0}%`}}/><span className="damaged" style={{width:`${items.length?damaged/items.length*100:0}%`}}/></div>{plan.pendingVendorApproval&&<p className="retention-note">Cần BGĐ duyệt xong các đơn vị đề xuất trước khi bắt đầu thực hiện kế hoạch.</p>}
 <div className="table-scroll"><table className="data-table catalog-table tracking-table"><thead><tr><th>Thiết bị / khoa</th><th>Đơn vị bảo trì</th><th>Tiến độ</th><th>Cập nhật / ghi chú</th><th>Thao tác</th></tr></thead><tbody>{items.map(row=>{const canWork=row.status==='IN_MAINTENANCE'&&row.execution_id&&plan.status==='IN_PROGRESS';const value=changes[row.item_id]??{status:row.progress_status==='NOT_STARTED'?'IN_PROGRESS':row.progress_status,note:''};return <tr key={row.item_id} className={row.progress_status==='DAMAGE_DETECTED'?'tracking-damage-row':row.progress_status==='WORK_DONE'?'tracking-done-row':''}><td><strong>{row.equipment_code} · {row.equipment_name}</strong><span className="row-sub">{row.department_name}</span></td><td>{row.provider_name || 'Chờ phê duyệt đơn vị'}</td><td>{canWork?<select aria-label={`Tiến độ ${row.equipment_code}`} value={value.status} disabled={busy!==null} onChange={e=>change(row,{status:e.target.value as MaintenanceProgressStatus})}>{Object.entries(progressLabels).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select>:<StatusBadge label={row.progress_status==='NOT_STARTED'?'Chưa bắt đầu':progressLabels[row.progress_status]} tone={row.progress_status==='WORK_DONE'?'teal':row.progress_status==='DAMAGE_DETECTED'?'amber':'neutral'}/>}</td><td>{canWork&&<textarea rows={2} aria-label={`Ghi chú ${row.equipment_code}`} placeholder={value.status==='DAMAGE_DETECTED'?'Mô tả hỏng hóc (bắt buộc)':'Ghi chú kết quả bảo trì…'} value={value.note} disabled={busy!==null} onChange={e=>change(row,{note:e.target.value})}/>}<span className="row-sub">{dateTime(row.updated_at ?? row.started_at)}</span>{row.work_note&&<p className="tracking-note">{row.work_note}</p>}</td><td><div className="table-actions">{['UNDER_CONTRACT','ASSIGNED_EXTERNAL','REWORK_REQUIRED'].includes(row.status)&&['APPROVED','IN_PROGRESS'].includes(plan.status)&&<button className="button primary compact" disabled={busy!==null||!!plan.pendingVendorApproval} onClick={()=>start(row)}>Bắt đầu bảo trì</button>}{canWork&&<button className="button secondary compact" disabled={busy!==null} onClick={()=>update(row)}>Lưu tiến độ</button>}<Link className="text-link" to={`/plans/${plan.id}/items/${row.item_id}/execution`}>Xem / cập nhật tiến độ</Link></div></td></tr>})}</tbody></table></div>
 <div className="maintenance-completion-panel"><div><h3>{plan.status==='AWAITING_REPORT'?'Bảo trì đã hoàn thành':'Xác nhận kết quả bảo trì'}</h3><p>{plan.status==='AWAITING_REPORT'?'Kế hoạch sẵn sàng lập, hoàn tất và gửi báo cáo.':ready?'Tất cả thiết bị đã có kết quả. VTYT có thể xác nhận hoàn thành và tạo báo cáo.':'Cập nhật “Bảo trì xong” hoặc “Có hỏng hóc” cho tất cả thiết bị trước khi hoàn thành.'}</p></div>{plan.status==='AWAITING_REPORT'?<Link className="button primary" to={`/plans/${plan.id}/report`}>Mở báo cáo bảo trì</Link>:<button className="button primary" disabled={!ready||busy!==null} onClick={complete}>Hoàn thành bảo trì & tạo báo cáo</button>}</div>
 </section></>:null}</div>
}
