import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router'
import { apiRequest } from '../api/client'
import { WorkflowError } from '../components/WorkflowFeedback'
import { EquipmentWarrantyTable, WarrantyBadge, WarrantyPeriod } from '../components/EquipmentWarrantyTable'
import { businessDate } from '../utils/workflowLabels'
import { EquipmentHistoryPage } from './EquipmentHistoryPage'
import type { CatalogEquipment } from '../types/equipmentCatalog'
export function QuarterlyEquipmentListPage() {
 const [rows, setRows] = useState<CatalogEquipment[]>([]); const [search, setSearch] = useState(''); const [department, setDepartment] = useState(''); const [status, setStatus] = useState(''); const [error, setError] = useState<unknown>(null); const [loading,setLoading]=useState(true)
 useEffect(() => { let active = true; apiRequest<CatalogEquipment[]>('/api/equipment-catalog').then(r => { if (active) {setRows(r);setLoading(false)} }).catch(e => { if (active) {setError(e);setLoading(false)} }); return () => { active = false } }, [])
 const visible=rows.filter(r=>`${r.equipment_code} ${r.equipment_name}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')) && (!department || r.department_name===department) && (!status || (r.warranty_status ?? 'UNRECORDED')===status))
 return <div className="page-stack catalog-page"><div className="catalog-hero"><div><p className="eyebrow">DANH MỤC THIẾT BỊ Y TẾ</p><h1>Danh sách thiết bị</h1><p>Tra cứu thiết bị, thời hạn bảo hành và lịch bảo trì của từng khoa/phòng.</p></div><span className="catalog-hero-symbol" aria-hidden="true">+</span></div><WorkflowError error={error}/>
  <div className="catalog-stats"><div><span>Tổng thiết bị</span><strong>{rows.length}</strong></div><div><span>Bảo hành còn hạn</span><strong>{rows.filter(r=>r.warranty_status==='VALID').length}</strong></div><div><span>Bảo hành hết hạn</span><strong>{rows.filter(r=>r.warranty_status==='EXPIRED').length}</strong></div><div><span>Chưa cập nhật thời hạn</span><strong>{rows.filter(r=>!r.warranty_end_date).length}</strong></div></div>
  <section className="panel business-panel catalog-panel"><div className="catalog-toolbar"><label>Tìm thiết bị<input type="search" placeholder="Nhập mã hoặc tên thiết bị…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Khoa/Phòng<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Tất cả khoa/phòng</option>{[...new Set(rows.map(r=>r.department_name))].sort().map(d=><option key={d}>{d}</option>)}</select></label><label>Bảo hành<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="VALID">Còn hạn</option><option value="EXPIRED">Hết hạn</option><option value="UNRECORDED">Chưa cập nhật</option></select></label></div><div className="panel-heading"><h2>Thiết bị hiện có</h2><span className="muted">{visible.length} / {rows.length} thiết bị</span></div>{loading?<p className="muted">Đang tải thiết bị…</p>:visible.length?<EquipmentWarrantyTable rows={visible}/>:<p className="empty-state">Không có thiết bị phù hợp với bộ lọc.</p>}<p className="catalog-footnote">Ngày bảo hành lấy từ hồ sơ thiết bị; thời hạn hợp đồng bảo trì được hiển thị riêng trong trang chi tiết.</p></section>
 </div>
}
export function EquipmentDetailPage() {
 const id = Number(useParams().equipmentId); const [row, setRow] = useState<CatalogEquipment | null>(null); const [error, setError] = useState<unknown>(null)
 useEffect(() => { let active = true; apiRequest<CatalogEquipment>(`/api/equipment/${id}/quarterly-detail`).then(r => { if (active) setRow(r) }).catch(e => { if (active) setError(e) }); return () => { active = false } }, [id])
 return <div className="page-stack catalog-page"><Link className="text-link" to="/equipment">← Danh sách thiết bị</Link><div className="catalog-hero"><div><p className="eyebrow">HỒ SƠ THIẾT BỊ</p><h1>{row?.equipment_name || 'Chi tiết thiết bị'}</h1><p>{row?.equipment_code} · {row?.department_name}</p></div>{row && <WarrantyBadge row={row}/>}</div><WorkflowError error={error}/>{row && <><section className="panel business-panel"><h2>Thông tin thiết bị</h2><div className="equipment-detail-grid"><div><span>Mã thiết bị</span><strong>{row.equipment_code}</strong></div><div><span>Khoa/Phòng</span><strong>{row.department_name}</strong></div><div><span>Thời hạn bảo hành</span><WarrantyPeriod row={row}/></div><div><span>Lịch bảo trì định kỳ</span><div className="quarter-badges">{row.quarters?.split(', ').map(q=><span key={q}>{q}</span>)}</div></div></div></section><section className="panel business-panel"><h2>Hợp đồng / công ty</h2>{row.contracts?.length ? <div className="table-scroll"><table className="data-table catalog-table"><thead><tr><th>Công ty</th><th>Hợp đồng</th><th>Ngày bắt đầu</th><th>Ngày hết hạn</th><th>Trạng thái</th></tr></thead><tbody>{row.contracts.map(c=><tr key={c.contract_id}><td><Link to={`/providers/${c.provider_id}`}>{c.provider_name}</Link></td><td><Link className="table-link" to={`/contracts/${c.contract_id}`}>{c.contract_code}</Link><span className="row-sub">{c.contract_name}</span></td><td>{businessDate(c.start_date)}</td><td>{businessDate(c.end_date)}</td><td>{c.valid?'Còn hạn':'Hết hạn'}</td></tr>)}</tbody></table></div>:<p className="empty-state">Chưa có hợp đồng bảo trì áp dụng.</p>}</section><section><h2>Lịch sử bảo trì</h2><EquipmentHistoryPage embedded/></section></>}</div>
}
